// ══════════════════════════════════════════════════════════════
// DartVault — Système de langue partagé (FR / EN)  v2
// ══════════════════════════════════════════════════════════════
(function () {
  const T = {
    fr: {
      // ── Header ──────────────────────────────────────────────
      menu:      '← Menu',
      back:      '← Retour',
      rules_btn: 'ℹ️',
      theme: 'Thème', theme_dark: '🌙 Sombre', theme_light: '☀️ Clair', theme_colored: '🎨 Coloré',
      vibrations: 'Vibrations', sounds: 'Sons', announcer: 'Annonceur',
      pp_title: '👤 CHOISIR UN PROFIL',
      pp_empty: 'Aucun profil enregistré.\nCrée-en un depuis le menu principal !',
      pp_cancel: 'Annuler',
      pp_manage: '＋ Gérer profils',
      pp_all_used: 'Tous les profils sont déjà en jeu.',

      // ── Setup commun ────────────────────────────────────────
      start:          'DÉMARRER',
      shuffle:        '🔀 Mélanger',
      player_ph:      'Nom du joueur',
      add_player:     '+ Ajouter',
      players_label:  '👥 Joueurs',
      mode_label:     '🎮 Mode',
      format_label:   '🏆 Format',
      rounds_label:   'MANCHES',
      sets_label:     'SETS',
      sets_sub:       '(3 manches/set)',
      diff_label:     '⚔️ Difficulté',
      easy_btn:       '😊 Facile',
      normal_btn:     '⚔️ Normal',

      // ── Modes solo/équipe ───────────────────────────────────
      solo_2_3:  'Solo (2-3)',
      solo_2_4:  'Solo (2-4)',
      solo_2_6:  'Solo (2-6)',
      solo_2:    'Solo (2)',
      team_2_4:  'Équipe (2-4)',
      team_2_6:  'Équipe (2-6)',

      // ── Labels équipes ──────────────────────────────────────
      team_blue:    '🔵 ÉQUIPE BLEUE',
      team_yellow:  '🟡 ÉQUIPE JAUNE',
      team_purple:  '🟣 ÉQUIPE VIOLETTE',
      player_blue:  '🔵 JOUEUR BLEU',
      player_yellow:'🟡 JOUEUR JAUNE',
      player_purple:'🟣 JOUEUR VIOLET',
      // noms courts (JS dynamique)
      blue:     'BLEU',
      yellow:   'JAUNE',
      purple:   'VIOLET',
      bleue:    'Bleue',
      jaune:    'Jaune',
      violette: 'Violette',
      // noms complets dynamiques
      team_a_full:  'ÉQUIPE BLEUE 🔵',
      team_b_full:  'ÉQUIPE JAUNE 🟡',
      player_c_full:'JOUEUR VIOLET 🟣',

      // ── Jeu commun ──────────────────────────────────────────
      undo:        'ANNULER',
      undo_cap:    'ANNULER',
      undo_last:   '↩ Annuler le dernier tir',
      validate:    'VALIDER',
      out:         'RATÉ',
      bull:        'BULL',
      history:     '📜 Historique',
      history_cap: '📜 HISTORIQUE',
      quick_sel:   'Sélection rapide',
      legend_btn:  '📖 Légende',
      legend_cap:  '📖 LÉGENDE',
      zones_btn:   '🗺️ Zones',
      zones_cap:   '🗺️ ZONES',
      single:      'Simple',
      double:      'Double',
      triple:      'Triple',
      zone_lbl:    'Zone',
      center:      'Centre',
      round_lbl:   'Tour',
      player_col:  'Joueur',

      // ── Quitter ─────────────────────────────────────────────
      quit_title:  '⚠️ Quitter la partie ?',
      quit_short:  '⚠️ Quitter ?',
      quit_sub:    'La partie en cours sera perdue.',
      quit_yes:    '🚪 Quitter',
      quit_no:     '▶️ Continuer',
      continue_btn:'Continuer',

      // ── Fin de partie ────────────────────────────────────────
      rematch:      '🔄 Revanche',
      config:       '⚙️ Configuration',
      cancel:       'Annuler',
      close:        'Fermer',
      rules_ok:     'OK',
      rules_hide:   'Cacher lors du lancement',
      end_title:    'FIN',
      results:      'Résultats',
      next_round:   '➡️ Manche suivante',
      hist_rounds:  '📋 Historique des manches',
      hist_shots:   '📋 Historique des coups',
      congrats:     'FÉLICITATIONS !',

      // ── 501 ─────────────────────────────────────────────────
      x01_mode:       '🎯 Mode de jeu',
      x01_entry:      '📝 Saisie',
      x01_total:      'Total',
      x01_endgame:    '🏁 Fin de partie',
      x01_doubleout:  'Double Out',
      x01_simpleout:  'Simple Out',
      x01_dblindblout:'D. In / D. Out',
      x01_di_q:       'Double In ?',
      x01_di_sub:     'As-tu touché un double ce tour ?',
      x01_di_yes:     '✅ Oui, double réalisé',
      x01_di_no:      '🚫 Non, pas de double',
      x01_di_cancel:  '↩ Annuler la saisie',
      x01_di_miss:    '🎯 Double In raté',
      x01_format:     '🏆 Format',
      x01_stats_chk:  '📊 Suivi stats Double Out %',
      x01_players:    '👥 Joueurs (1-6)',
      x01_avg:        'MOY',
      x01_best:       'BEST',
      x01_chip_darts: 'DARTS',
      x01_darts:      'FLÉCHETTES',
      x01_prev:       'TOUR PRÉC.',
      x01_finish:     '💡 FINISH :',
      x01_dart1:      'FLÉCHETTE 1/3',
      x01_single_x:   'SIMPLE ×1',
      x01_double_x:   'DOUBLE ×2',
      x01_triple_x:   'TRIPLE ×3',
      x01_25bull:     '25/Bull',
      x01_stats_cap:  '📊 STATISTIQUES',
      x01_checkout:   '🎯 CHECKOUT !',
      x01_checkout_q: 'Confirmer le finish ?',
      x01_checkout_y: '✅ Oui, gagné !',
      x01_checkout_n: '❌ Non, annuler',
      x01_dbl_tries:  '🎯 Tentatives Double Out',
      x01_dbl_q:      'Combien de doubles as-tu visé ce tour ?',
      x01_bigfish:    'BIG FISH',
      x01_bigfish_sub:'Finish 170 — Le maximum possible !',
      x01_bigfish_btn:'Incroyable !',
      x01_menu_btn:   '🏠 Menu',
      x01_no_history: 'Aucun coup joué.',
      x01_legs_label: 'manches',
      x01_throws_hist:'HISTORIQUE DES VOLÉES',
      x01_hist_title: 'HISTORIQUE',
      x01_rounds_dlg: 'Nombre de manches',
      x01_rules_title:'🎯 RÈGLES X01',
      x01_rules_obj:  'Objectif :',
      x01_rules_obj_t:'Réduire son score à exactement 0.',
      x01_rules_bust: 'Bust :',
      x01_rules_dbl:  'Double Out :',
      x01_rules_dbl_t:'Le dernier tir doit être une double (D1–D20 ou Bull 50).',
      x01_rules_spl:  'Simple Out :',
      x01_rules_spl_t:"On peut finir sur n'importe quelle zone.",
      x01_rules_max:  'Score max par volée :',
      x01_rules_fin:  'Finish :',
      x01_rules_fin_t:'Suggestions affichées dès 170 pts ou moins.',

      // ── Cricket ──────────────────────────────────────────────
      ckt_mode:       '🎯 Mode de jeu',
      ckt_std:        'Standard',
      ckt_cut:        'Cut-throat',
      ckt_noscore:    'No Score',
      ckt_random:     'Zones aléatoires',
      ckt_tours:      '⏱️ Tours par manche',
      ckt_players:    '👥 Joueurs (2-6)',
      ckt_players_ns: '👥 Joueurs (1-6)',
      ckt_rounds_dlg: 'Nombre de manches',
      ckt_continue:   '▶ Continuer',
      ckt_end:        '🏆 FIN DE PARTIE',
      ckt_hist:       '📜 HISTORIQUE',
      ckt_rules_title:'🦗 Règles du Cricket',
      ckt_rules_nums: 'Numéros du Cricket',
      ckt_rules_bull: 'BULL',
      ckt_rules_marks:'Marques',
      ckt_rules_m_sub:'3 fléchettes dans un numéro = fermé.',
      ckt_rules_pts:  'Points',
      ckt_rules_win:  'Victoire — Standard',
      ckt_rules_win_t:'Fermer tous les numéros avec le plus de points.',
      ckt_rules_cut:  '⚔️ Cut-throat',
      ckt_rules_cut_t:'moins de points',
      ckt_rules_cut_t2:'à la fermeture gagne.',
      ckt_rules_ns:   '🚫 No Score',
      ckt_rules_ns_t: 'Pas de points. Le premier joueur à fermer tous les numéros gagne. Vitesse pure !',
      ckt_rules_btns: 'Boutons',
      ckt_rules_out:  'OUT',
      ckt_rules_out_t:'= fléchette hors cricket, consomme une fléchette.',
      ckt_rules_rnds: 'Manches',
      ckt_rules_wh:   '🐎 White Horse',
      ckt_rules_wh_t: '3 Triples dans le même tour sur des zones totalement vierges',
      ckt_rules_wh_t2:"(aucun joueur n'a encore touché ces zones) déclenche le légendaire White Horse !",
      ckt_whitehorse: 'WHITE HORSE',
      ckt_wh_sub:     '3 Triples sur zones vierges dans le même tour — Légendaire !',
      ckt_wh_sub2:    'Impressionnant !',
      ckt_leg_abbr:   'M',
      ckt_legs_label: 'manches',
      ckt_set_abbr:   'S',
      ckt_out_lbl:    'Raté',
      ckt_adv:        'adv',

      // ── Shanghai ─────────────────────────────────────────────
      shg_rounds:     '🎯 MANCHES',
      shg_mode_lbl:   '🎯 MODE DE JEU',
      shg_mode_std:   'Standard',
      shg_mode_rnd:   'Aléatoire',
      shg_sectors_lbl:'🔺 NOMBRE DE SECTEURS',
      shg_players:    '👥 Joueurs (2-6)',
      shg_round_lbl:  'MANCHE {r}/{t}',
      shg_round_abbr: 'M',
      shg_target:     'CIBLE',
      shg_single:     'SIMPLE',
      shg_s_pts:      '+1 pts',
      shg_double:     'DOUBLE',
      shg_d_pts:      '+2 pts',
      shg_triple:     'TRIPLE',
      shg_t_pts:      '+3 pts',
      shg_hist:       '📜 HISTORIQUE',
      shg_event:      'SHANGHAI !',
      shg_event_sub:  'Simple + Double + Triple du',
      shg_event_sub2: '— Légendaire !',
      shg_confirm:    '🎆 Valider le Shanghai !',
      shg_cancel_shot:'↩ Annuler le tir',
      shg_recap:      'Récap',
      shg_rules_title:'🎯 RÈGLES SHANGHAI',
      shg_rules_obj:  'Objectif :',
      shg_rules_obj_t:'Marquer le maximum de points en 7 manches. Chaque manche a une cible (1 à 7 en mode Standard, ou aléatoire en mode Aléatoire).',
      shg_rules_shg:  'Shanghai :',
      shg_rules_shg_t:'Toucher Simple + Double + Triple de la même cible en un seul tour = victoire immédiate !',
      shg_rules_out:  'OUT :',
      shg_rules_out_t:'Fléchette hors cible, 0 point.',
      shg_rules_end:  'Fin :',
      shg_rules_end_t:'Après toutes les manches, le joueur avec le plus de points gagne.',

      // ── Territoire ───────────────────────────────────────────
      ter_zones:      '🎯 Nombre de zones',
      ter_rounds:     '⏱️ Nombre de manches',
      ter_mode:       '🎮 Mode de jeu',
      ter_solo:       'Solo (2-3)',
      ter_team:       'Équipe (2-6)',
      ter_diff:       '⚔️ Difficulté',
      ter_players:    '👥 Joueurs (2-3)',
      ter_round_lbl:  'MANCHE {r}/{t}',
      ter_bull_title: '🎯 Zone Bull',
      ter_bull_q:     'Quelle zone as-tu touchée ?',
      ter_small_bull: '🟢 Small Bull (25)',
      ter_bull50:     '🔴 Bull (50)',
      ter_mult_zone:  'Zone',
      ter_rules_title:'🏰 RÈGLES DU JEU',
      ter_rules_obj:  '🎯 Objectif',
      ter_rules_obj_t:'Capturer un maximum de zones. Gagner en contrôlant toutes les zones ou en en possédant le plus à la fin des manches.',
      ter_rules_sd:   'Simple / Double',
      ter_rules_sd_t: '→ Capture la zone neutre ou neutralise une zone ennemie',
      ter_rules_sd_t2:"→ Capture directe d'une zone ennemie sans bouclier",
      ter_rules_tn:   'Triple sur zone neutre',
      ter_rules_tn_t: '→ Capture + 🛡️ bouclier ajouté',
      ter_rules_ty:   'Triple sur votre zone',
      ter_rules_ty_t: '→ Ajoute un 🛡️ bouclier',
      ter_rules_sh:   '🛡️ Bouclier',
      ter_rules_sh_t: "Protège la zone d'une attaque simple/double",
      ter_rules_bull: '🔄 Tour de jeu',
      ter_rules_bull_t:'3 fléchettes par joueur, puis passage au suivant. Nouvelle manche quand tous les joueurs ont joué.',

      // ── DartPong ────────────────────────────────────────────
      dp_zones:       '🎯 Zones',
      dp_diff:        '⚔️ Difficulté',
      dp_mode:        '🎮 Mode de jeu',
      dp_solo:        'Solo (2-6)',
      dp_team:        'Équipe (2-6)',
      dp_options:     '🎉 OPTIONS',
      dp_party:       'Mode Soirée',
      dp_players:     '👥 Joueurs (2-6)',
      dp_bull_title:  '🎯 Annoncer le BULL ?',
      dp_bull_q:      'Avez-vous annoncé le bull avant de tirer ?',
      dp_bull_yes:    '✅ OUI',
      dp_bull_no:     '❌ NON',
      dp_confirm_t:   'Double 18 ?',
      dp_confirm_q:   'Valider ce tir ?',
      dp_confirm_y:   '✅ Oui',
      dp_confirm_n:   '❌ Non',
      dp_exploit:     '🔥 EXPLOIT !',
      dp_exploit_sub: "3 zones éliminées d'affilée !",
      dp_bonus:       '⚡ BONUS : REJOUE UN TOUR COMPLET ⚡',
      dp_replay:      'OK — REJOUER',
      dp_party_title: '🎉 MODE SOIRÉE !',
      dp_party_miss:  'Tu as raté !',
      dp_party_drink: '🍺 Boire un coup',
      dp_party_lose:  '⏭️ Perdre une fléchette',
      dp_zones_left:  '🗺️ ZONES RESTANTES',
      dp_rules_title: '🍺 RÈGLES DARTPONG',
      dp_rules_obj:   'Objectif :',
      dp_rules_obj_t: "Éliminer toutes ses zones avant l'adversaire.",
      dp_rules_zones: 'Zones :',
      dp_rules_str:   '🔥 Streak x3 :',
      dp_rules_str_t: "Éliminer 3 zones d'affilée = rejouer un tour complet !",
      dp_rules_bull:  '🎯 Bull (annoncé) :',
      dp_rules_bull_t:"Élimine 2 zones aléatoires de son équipe. Doit être annoncé avant le tir, utilisable une seule fois par équipe.",
      dp_rules_party: '🎉 Mode Soirée :',
      dp_rules_party_t:"Sur une zone neutre (zone adverse ou hors-zone), choisir entre un gage ou perdre sa prochaine fléchette.",
      dp_rules_3d:    '3 fléchettes',
      dp_rules_3d_t:  'par joueur par tour.',

      // ── Shooter (Battle Royal) ───────────────────────────────
      sht_hp:         '❤️ POINTS DE VIE',
      sht_diff:       '⚔️ DIFFICULTÉ',
      sht_mode:       '🎮 Mode de jeu',
      sht_solo:       'Solo (2-4)',
      sht_team:       'Équipe (2-4)',
      sht_players:    '👥 Joueurs (2-4)',
      sht_turn:       'TOUR 1',
      sht_last_title: '⚠️ LAST STAND',
      sht_last_sub:   'Tu es tombé à 1 PV ! Choisis ta zone de survie :',
      sht_undo_last:  '↩ Annuler le dernier tir',
      sht_hist:       '📜 HISTORIQUE',
      sht_rules_title:'💥 RÈGLES BATTLE ROYAL',
      sht_rules_obj:  '🎯 Objectif :',
      sht_rules_obj_t:'Être le dernier survivant (ou équipe)',
      sht_rules_dead: 'Tombe à 0 → éliminé',
      sht_rules_ammo: '💥 Balles :',
      sht_rules_a_t:  'Nécessaires pour attaquer',
      sht_rules_bul1: '💚 Bull vert :',
      sht_rules_bul1t:'+2 PV ou soins/résurrection',
      sht_rules_bul2: '❤️ Bull rouge :',
      sht_rules_bul2t:'Supprime invulnérabilités + choix bonus',
      sht_rules_inv:  '🛡️ Invulnérabilité :',
      sht_rules_inv_t:'Ignore dégâts (1 tour)',
      sht_rules_ls:   '⚠️ Last Stand (mode facile) :',
      sht_rules_ls_t: 'À 1 PV, choisis 1 zone de survie',
      sht_leg_zones:  '🎯 Zones :',
      sht_leg_own:    'Ta zone',
      sht_leg_own_t:  ': Recharge +1/2/3 💥 (simple/triple/double)',
      sht_leg_enemy:  'Zone ennemie',
      sht_leg_enemy_t:': -1 balle, inflige 1/2/3 dégâts',
      sht_leg_neutral:'Zone neutre',
      sht_leg_neut_t: ': Raté, -1 balle',
      sht_leg_bulls:  '🐂 Bulls :',
      sht_leg_grbull: '💚 Vert',
      sht_leg_grb_t:  ': +2 HP ou ressusciter allié',
      sht_leg_rdbull: '❤️ Rouge',
      sht_leg_rdb_t:  ': Retire invulnérabilités, puis +2 HP ou immunité',

      // ── Blackjack ────────────────────────────────────────────
      bj_rounds:      '🎯 MANCHES',
      bj_min:         '📉 MIN',
      bj_max:         '📈 MAX',
      bj_players:     '👥 Joueurs (2-6)',
      bj_rnd_dealer:  '🎲 Croupier aléatoire',
      bj_dealer_hint: '🎩 Appuie sur',
      bj_dealer_btn:  'Croupier',
      bj_dealer_hint2:'pour désigner manuellement, ou utilise le bouton aléatoire.',
      bj_target:      'Score cible',
      bj_round_lbl:   'MANCHE {r}/{t}',
      bj_round_label: 'Manche {r}/{t}',
      bj_players_col: 'Joueurs',
      bj_dealer_cap:  '🎩 CROUPIER',
      bj_bj_title:    'BLACKDART !',
      bj_bj_sub:      'Score parfait — exactement la cible ! 🎯',
      bj_bj_sub2:     'Incroyable !',
      bj_hist_rounds: '📋 Historique des manches',
      bj_rules_title: '🎰 RÈGLES BLACKDART',
      bj_rules_obj:   'Objectif :',
      bj_rules_obj_t: 'Avoir le score le plus proche du score cible sans le dépasser.',
      bj_rules_tgt:   'Cible :',
      bj_rules_tgt_t: 'Nombre aléatoire entre 21 et 80, différent à chaque manche.',
      bj_rules_dealer:'Désignation du croupier :',
      bj_rules_dlr_t: 'Choisissez manuellement ou tirez au sort. Le croupier reste le même toute la partie.',
      bj_rules_res:   'Résultats :',
      bj_rules_r1:    'Score parfait (= cible) → +2€ (si croupier parfait aussi : égalité)',
      bj_rules_r2:    'Meilleur que le croupier → +1€',
      bj_rules_r3:    'Moins bon que le croupier → -1€',
      bj_rules_r4:    'Dépasser la cible → score = 0',
      bj_rules_r5:    'Si croupier parfait : tous les autres joueurs -2€.',

      // ── Race 500 ─────────────────────────────────────────────
      rc_target:      '🏁 Score cible',
      rc_steal_cfg:   '🎯 Points volés',
      rc_steal_off:   'Aucun',
      rc_players:     '👥 Joueurs (2-6)',
      rc_turn:        'TOUR 1 · FLÉCHETTE 1/3',
      rc_single_x:    'SIMPLE ×1',
      rc_double_x:    'DOUBLE ×2',
      rc_triple_x:    'TRIPLE ×3',
      rc_25bull:      '25/Bull',
      rc_bust_title:  '💥 BUST !',
      rc_bust_sub:    'Fléchette annulée.',
      rc_end_title:   '🏁 ARRIVÉE !',
      rc_hist:        '📋 Historique des coups',
      rc_rules_title: '🏁 RÈGLES RACE',
      rc_rules_obj:   'Objectif :',
      rc_rules_obj_t: 'Être le premier à atteindre exactement le score cible (300 ou 500).',
      rc_rules_turn:  'Tour :',
      rc_rules_turn_t:'3 fléchettes. Points = numéro × multiplicateur.',
      rc_rules_bust:  'Bust :',
      rc_rules_bust_t:'Dépasser la cible annule tout le tour.',
      rc_rules_steal: 'Vol :',
      rc_rules_steal_t:"Atterrir sur le score exact d'un adversaire lui vole des points (configurable) !",
      rc_rules_out:   'OUT :',
      rc_rules_out_t: '0 pt, compte comme une fléchette.',

      // ── Bataille Navale ──────────────────────────────────────
      bt_ships:         '🚢 Nombre de bateaux',
      bt_mode:          '🎮 Mode de jeu',
      bt_solo:          'Solo (2)',
      bt_team:          'Équipe (2-6)',
      bt_players:       '👥 Joueurs (2)',
      bt_team_blue:     '🔵 ÉQUIPE BLEUE',
      bt_team_yellow:   '🟡 ÉQUIPE JAUNE',
      bt_handoff_title: 'Passe le téléphone',
      bt_handoff_sub:   "C'est au tour de l'équipe de placer ses bateaux en secret.",
      bt_handoff_btn:   "C'est parti !",
      bt_attack_title:  '📱 Passe le téléphone',
      bt_attack_sub:    "C'est au tour de l'équipe d'attaquer !",
      bt_attack_btn:    '⚔️ Je suis prêt !',
      bt_place_hint1:   'Touche une zone pour placer un bateau (3 cases adjacentes)',
      bt_place_hint2:   'Tape sur la cible pour choisir la case centrale du bateau',
      bt_confirm_title: '🎯 Confirmer le tir',
      bt_confirm_q:     'Valider ce tir ?',
      bt_confirm_zone:  'Zone : —',
      bt_confirm_yes:   "✅ Oui, c'est bien ça",
      bt_confirm_no:    '↩ Non, annuler',
      bt_bull_title:    '🎯 Zone Bull',
      bt_bull_q:        'Quelle zone as-tu touchée ?',
      bt_small_bull:    '🟢 Small Bull (25)',
      bt_bull50:        '🔴 Bull (50)',
      bt_win:           '🏆 VICTOIRE !',
      bt_quit:          '⚠️ Quitter ?',
      bt_blue_lbl:      '⚓ BLEU',
      bt_yellow_lbl:    '⚓ JAUNE',
      bt_blue_team:     'Bleue',
      bt_yellow_team:   'Jaune',
      bt_blue_team_cap: 'BLEU',
      bt_yellow_team_cap:'JAUNE',
      bt_place_title:   'Équipe Bleue — Placement',
      bt_hist:          '📜 HISTORIQUE',
      bt_rules_title:   '⚓ Règles — Bataille Navale',
      bt_rules_princ:   '🎯 Principe',
      bt_rules_ships:   '🚢 Bateaux',
      bt_rules_zones:   '🗺️ Zones de tir',
      bt_rules_bull:    '🎯 Bull & Small Bull',
      bt_rules_res:     '💥 Résolution',
      bt_rules_win:     '🏆 Victoire',
      bt_rules_win_t:   'Première équipe à couler tous les bateaux adverses.',
      bt_rules_got:     'Compris !',
      bt_leg_hit:       'TOUCHÉ',
      bt_leg_hit_t:     'La fléchette a atteint une case contenant un bateau adverse',
      bt_leg_sink:      'COULÉ',
      bt_leg_sink_t:    'Les 3 cases du bateau ont toutes été touchées — bateau détruit',
      bt_leg_miss:      'RATÉ',
      bt_leg_miss_t:    'Aucun bateau adverse sur cette case (case vide, propre bateau ou doublon)',
      bt_leg_intact:    'BATEAU INTACT',
      bt_leg_intact_t:  'Bateau encore en jeu dans la flotte',
      bt_leg_sunk:      'BATEAU COULÉ',
      bt_leg_sunk_t:    'Bateau hors jeu — toutes ses cases ont été touchées',
      bt_leg_sb:        'SMALL BULL (25)',
      bt_leg_sb_t:      'Cercle vert extérieur — révèle 2 cases aléatoires non encore tirées',
      bt_leg_bull:      'BULL (50)',
      bt_leg_bull_t:    'Cercle rouge intérieur — révèle 3 cases aléatoires non encore tirées',

      // ── Clés dynamiques ajoutées ─────────────────────────────
      x01_impossible:   'Score impossible',
      x01_stat_busts:   'Dépassements',
      x01_bust_hint:    '💥 BUST — tour annulé',
      x01_bust_one:     '💥 BUST — reste 1 (impossible)',
      x01_remaining:    'Reste : ',
      x01_hit_double:   'a touché une double ?',
      x01_finishes:     'finit la partie !',
      x01_score_colon:  'Score : ',
      x01_bust_toast:   '💥 BUST ! Score inchangé.',
      x01_stat_moyenne: 'Moyenne',
      x01_stat_best:    'Meilleure volée',
      x01_stat_dout:    'Double Out %',
      x01_stat_darts:   'Fléchettes',
      x01_stat_remaining:'Score restant',
      x01_no_shots:     'Aucun lancer enregistré',
      x01_sets_dlg:     'Nombre de sets',
      ckt_draw:         'ÉGALITÉ !',
      ckt_wins_set:     'remporte le set !',
      ckt_wins_leg:     'remporte la manche !',
      ckt_sets_colon:   'Sets : ',
      ckt_legs_in_set:  'Manches dans le set : ',
      shg_wins:         'remporte la partie !',
      shg_draw:         '🤝 ÉGALITÉ !',
      shg_wins_short:   'gagne !',
      ter_victory:      'VICTOIRE !',
      ter_total_control:'Contrôle total des territoires !',
      ter_draw:         'ÉGALITÉ !',
      ter_hist_captured:'capturée',
      ter_hist_captured_shield:'capturée + 🛡️',
      ter_hist_shield_added:'+ 🛡️',
      ter_hist_allied:  'alliée (rien)',
      ter_hist_shield_neutral:'🛡️ brisé + neutralisée',
      ter_hist_shield_broken:'🛡️ brisé',
      ter_hist_direct:  'capture directe',
      ter_hist_neutral: 'neutralisée',
      dp_sector:        'Secteur',
      dp_simple_ext:    'Simple ext.',
      dp_simple_int:    'Simple int.',
      dp_not_started:   'Partie non démarrée',
      dp_all_eliminated:'Toutes éliminées !',
      sht_allied_zone:  'zone alliée',
      sht_invuln_toast: 'Invulnérable !',
      sht_eliminated:   'ÉLIMINÉ',
      sht_last_active:  'Last Stand actif',
      sht_last_toast:   'Last Stand !',
      sht_invuln_hist:  'Invulnérable (retire les autres)',
      sht_invuln_hist_suffix:'(retire les autres)',
      sht_invuln_expire:'Invuln expire',
      sht_invuln_expire_dead:'Invuln expire (donneur éliminé)',
      sht_invuln_label: 'Invulnérabilité',
      sht_invuln_me:    'Invuln pour moi',
      sht_invuln_for:   'Invuln pour',
      sht_revive:       'Ressusciter',
      sht_to_1hp:       'à 1 HP',
      sht_to_2hp:       'à 2 HP',
      sht_last_zone:    'Last Stand zone',
      sht_stat_bullets: '💥 Balles',
      sht_stat_damage:  '🗡️ Dégâts',
      bj_below_target:  'sous la cible',
      bj_busted:        'dépassé!',
      bj_over_hint:     'Dépassé — score = 0',
      bj_score_colon:   'Score :',
      bj_balance_colon: 'Solde :',
      bj_round_lbl2:    'MANCHE {r}/{t}',
      rc_steal_lbl:     'VOL',
      rc_remaining:     'Reste : {n}',
      rc_steal_bust_lbl:'VOL BUST',
      rc_steal_toast:   '💥 {p} vole {pts} pts à {o} !',
      rc_exceeds:       'dépasse',
      rc_exceeds_steal: 'dépasse après vol',
      rc_cancelled:     'Tour annulé — retour à',
      rc_no_shots:      'Aucun coup joué',
      rc_stat_stolen:   'Volé :',
      rc_stat_lost:     'Perdu :',
      rc_pts_ahead:     'pts devant',
      rc_darts_abbr:    'flt',
      bt_placement_done:'Placement terminé',
      bt_pass_phone_team:"Passe le téléphone à l'Équipe {tn}.",
      bt_place_ships:   'Placez vos {n} bateaux en secret.',
      bt_current_ship:  'Bateau en cours',
      bt_to_place:      'À PLACER',
      bt_ships_placed:  'bateaux placés',
      bt_fleet_label:   'FLOTTE',
      bt_ring:          'anneau',
      bt_ring_ext:      'extérieur',
      bt_ring_int:      'intérieur',
      bt_ring_any:      'extérieur ou intérieur',
      bt_ring_ext_full: 'Anneau extérieur',
      bt_ring_int_full: 'Anneau intérieur',
      bt_leg_intact_desc: 'Bateau encore en jeu dans la flotte',
      bt_hit:           '💥 TOUCHÉ !',
      bt_sunk:          '💀 COULÉ !',
      bt_miss:          '💨 RATÉ',
      bt_dup_shot:      '💨 Déjà tiré — Raté !',
      bt_out_miss:      'raté',
      ter_header_title: '🏰 TERRITOIRE',
      bat_header_title: '⚓ BATAILLE NAVALE',
      bt_ship_ring_error:"Ce bateau doit être sur l'anneau",
      bt_team_wins:     'Équipe {team} gagne !',
      bt_ship_carrier:   '⚓ Porte-avion',
      bt_ship_sub:       '🤿 Sous-marin',
      bt_ship_free_any:  '🚢 Bateau libre',
      bt_ship_battleship:'🛳 Cuirassé',
      bt_ship_cruiser:   '⛵ Croiseur',
      bt_ship_libre:     '🚢 Libre',
      bt_ship_libre1:    '🚢 Libre 1',
      bt_ship_libre2:    '🚢 Libre 2',

      // ── Nouvelles clés dynamiques round 2 ───────────────────
      x01_dart1_info:   'FLÉCHETTE 1/3',
      x01_dart_n:       'FLÉCHETTE {n}/3',
      x01_turn_done:    '✅ Tour complet',
      x01_3darts_validate: 'Tour fini — Valider pour continuer',
      x01_set_won:      'Set remporté !',
      x01_leg_won:      'Manche remportée !',
      x01_match_score:  'SCORE DU MATCH',
      x01_sets_to_win:  'set(s) pour gagner',
      x01_legs_to_win:  'manche(s) pour gagner',
      x01_sets_lbl:     'sets',
      x01_legs_lbl:     'manches',
      x01_next_set:     '➡️ Set suivant',
      x01_wins_match:   'gagne le match !',
      x01_avg_lbl:      'Moy.',
      x01_per_dart:     'Par fléchette',
      x01_not_aimed:    'Pas visé',
      x01_attempt:      'tentative',
      x01_attempts:     'tentatives',
      ckt_no_winner:    'Personne ne remporte cette manche.',
      ckt_legs_simple:  'Manches : ',
      ter_teams_lbl:    'Équipes',
      dp_dart_lost:     'Fléchette perdue',
      dp_per_player:    'PAR JOUEUR',
      bj_end_title:     'FIN DE PARTIE',
      bj_wins_with:     'gagne avec',
      bj_no_rounds:     'Aucune manche jouée',
      bj_hist_round_lbl:'MANCHE {r}',
      rc_turn_info:     'TOUR {t} · FLÉCHETTE {d}/3',
      rc_wins:          'gagne la course !',
      rc_leading:       '1er',
      rc_to_finish:     'pour finir',
      bt_attack_turn:   "Équipe {team} — à toi d'attaquer ! (3 fléchettes)",

      // ── Règles 501 ────────────────────────────────────────
      x01_rules_title:  '🎯 RÈGLES X01',
      x01_r_obj:        '<strong style="color:var(--accent);">Objectif :</strong> Réduire son score à exactement 0.',
      x01_r_bust:       '<strong style="color:var(--accent);">Bust :</strong> Si le score descend en-dessous de 0 ou atteint 1 (Double Out), le tour est annulé et le score revient à sa valeur précédente.',
      x01_r_dout:       '<strong style="color:var(--ok);">Double Out :</strong> Le dernier tir doit être une double (D1–D20 ou Bull 50).',
      x01_r_sout:       '<strong style="color:var(--warn);">Simple Out :</strong> On peut finir sur n\'importe quelle zone.',
      x01_r_max:        '<strong style="color:var(--accent);">Score max par volée :</strong> 180 (T20 + T20 + T20).',
      x01_r_finish:     '<strong style="color:var(--accent);">Finish :</strong> Suggestions affichées dès 170 pts ou moins.',
      // ── Règles Cricket ────────────────────────────────────
      ckt_rules_title:  '🦗 Règles du Cricket',
      ckt_rules_nums:   'Numéros du Cricket',
      ckt_r_nums_t:     '15, 16, 17, 18, 19, 20 et <strong>BULL</strong>.',
      ckt_rules_marks:  'Marques',
      ckt_r_marks_t:    '3 fléchettes dans un numéro = fermé.<br><strong>/</strong> = 1 marque &nbsp;·&nbsp; <strong>X</strong> = 2 marques &nbsp;·&nbsp; <strong>✦</strong> = fermé',
      ckt_rules_pts:    'Points',
      ckt_r_pts_t:      'Une fois un numéro fermé, chaque marque supplémentaire rapporte des points tant que les adversaires ne l\'ont pas aussi fermé.',
      ckt_rules_win:    'Victoire — Standard',
      ckt_rules_win_t:  'Fermer tous les numéros avec le plus de points.',
      ckt_r_cutthroat:  'Tes points vont aux adversaires ! Quand tu marques sur un numéro fermé, les adversaires qui ne l\'ont pas encore fermé reçoivent les points. Le joueur avec le <strong>moins de points</strong> à la fermeture gagne.',
      ckt_r_noscore:    'Pas de points. Le premier joueur à fermer tous les numéros gagne. Vitesse pure !',
      ckt_r_btns_h:     'Boutons',
      ckt_r_btns_t:     '<strong>S ×1</strong> = Simple &nbsp;·&nbsp; <strong>D ×2</strong> = Double &nbsp;·&nbsp; <strong>T ×3</strong> = Triple<br><strong>OUT</strong> = fléchette hors cricket, consomme une fléchette.',
      ckt_r_legs_h:     'Manches',
      ckt_r_legs_t:     'En mode infini, la partie se termine quand un joueur ferme tous les numéros. En manches limitées (10, 15, 20), la partie s\'arrête à la dernière manche et le classement final détermine le vainqueur.',
      ckt_r_wh:         'Réaliser <strong>3 Triples dans le même tour sur des zones totalement vierges</strong> (aucun joueur n\'a encore touché ces zones) déclenche le légendaire White Horse !',
      // ── Règles Shanghai ───────────────────────────────────
      shg_rules_title:  '🎯 RÈGLES SHANGHAI',
      shg_r_obj:        '<strong style="color:var(--accent);">Objectif :</strong> Marquer le maximum de points en 7 manches. Chaque manche a une cible (1 à 7 en mode Standard, ou aléatoire en mode Aléatoire).',
      shg_r_scoring:    '<strong style="color:var(--ok);">Simple</strong> = valeur × 1 &nbsp;|&nbsp; <strong style="color:var(--ok);">Double</strong> = valeur × 2 &nbsp;|&nbsp; <strong style="color:var(--warn);">Triple</strong> = valeur × 3',
      shg_r_shanghai:   '<strong style="color:var(--warn);">Shanghai :</strong> Toucher Simple + Double + Triple de la même cible en un seul tour = victoire immédiate !',
      shg_r_out:        '<strong style="color:var(--dim);">OUT :</strong> Fléchette hors cible, 0 point.',
      shg_r_end:        '<strong>Fin :</strong> Après toutes les manches, le joueur avec le plus de points gagne.',
      // ── Règles Territoire ─────────────────────────────────
      ter_rules_title:  '🏰 RÈGLES DU JEU',
      ter_r_obj_h:      '🎯 Objectif',
      ter_r_obj_t:      'Capturer un maximum de zones. Gagner en contrôlant toutes les zones ou en en possédant le plus à la fin des manches.',
      ter_r_zones_h:    '🗺️ Zones',
      ter_r_z1:         '<strong>Simple / Double</strong> → Capture la zone neutre ou neutralise une zone ennemie',
      ter_r_z2:         '<strong>Triple</strong> → Capture directe d\'une zone ennemie sans bouclier',
      ter_r_z3:         '<strong>Triple sur zone neutre</strong> → Capture + 🛡️ bouclier ajouté',
      ter_r_z4:         '<strong>Triple sur votre zone</strong> → Ajoute un 🛡️ bouclier',
      ter_r_shield_h:   '🛡️ Bouclier',
      ter_r_sh1:        'Protège la zone d\'une attaque simple/double',
      ter_r_sh2:        'Un simple/double brise le bouclier sans capturer',
      ter_r_sh3:        'Un triple brise le bouclier ET neutralise la zone',
      ter_r_bull25_h:   '💚 Bull Vert (25 pts)',
      ter_r_bull25_t:   'Neutralise 2 zones ennemies aléatoires. Si une zone a un bouclier, il est brisé en premier.',
      ter_r_bull50_h:   "❤️ Bull Rouge (Bull's Eye)",
      ter_r_bull50_t:   'Capture une zone ennemie aléatoire + ajoute un 🛡️ bouclier.',
      ter_r_turn_h:     '🔄 Tour de jeu',
      ter_r_turn_t:     '3 fléchettes par joueur, puis passage au suivant. Nouvelle manche quand tous les joueurs ont joué.',
      // ── Règles DartPong ──────────────────────────────────
      dp_rules_title:   '🍺 RÈGLES DARTPONG',
      dp_r_obj:         '<strong style="color:var(--accent);">Objectif :</strong> Éliminer toutes ses zones avant l\'adversaire.',
      dp_r_zones:       '<strong style="color:var(--ok);">Zones :</strong> Chaque équipe a N zones aléatoires (simples, doubles ou triples). Pour éliminer une zone, il faut la toucher exactement.',
      dp_r_streak:      '<strong style="color:#FFD700;">🔥 Streak x3 :</strong> Éliminer 3 zones d\'affilée = rejouer un tour complet !',
      dp_r_bull:        '<strong style="color:#FFD700;">🎯 Bull (annoncé) :</strong> Élimine 2 zones aléatoires de son équipe. Doit être annoncé avant le tir, utilisable une seule fois par équipe.',
      dp_r_party:       '<strong style="color:var(--accent);">🎉 Mode Soirée :</strong> Sur une zone neutre (zone adverse ou hors-zone), choisir entre un gage ou perdre sa prochaine fléchette.',
      dp_r_darts:       '<strong style="color:var(--dim);">3 fléchettes</strong> par joueur par tour.',
      // ── Règles Shooter ────────────────────────────────────
      sht_rules_title:  '💥 RÈGLES BATTLE ROYAL',
      sht_r_obj:        '<strong>🎯 Objectif :</strong> Être le dernier survivant (ou équipe)',
      sht_r_hp:         '<strong>❤️ PV :</strong> Tombe à 0 → éliminé',
      sht_r_ammo:       '<strong>💥 Balles :</strong> Nécessaires pour attaquer',
      sht_r_ammo1:      '• Tir sur ta zone → +1/2/3 balles',
      sht_r_ammo2:      '• Attaque ennemie → -1 balle, 1/2/3 dégâts',
      sht_r_bullg:      '<strong>💚 Bull vert :</strong> +2 PV ou soins/résurrection',
      sht_r_bullr:      '<strong>❤️ Bull rouge :</strong> Supprime invulnérabilités + choix bonus',
      sht_r_invuln:     '<strong>🛡️ Invulnérabilité :</strong> Ignore dégâts (1 tour)',
      sht_r_last:       '<strong>⚠️ Last Stand (mode facile) :</strong> À 1 PV, choisis 1 zone de survie',
      // ── Règles Blackjack ──────────────────────────────────
      bj_rules_title:   '🎰 RÈGLES BLACKDART',
      bj_r_obj:         '<strong style="color:var(--gold);">Objectif :</strong> Avoir le score le plus proche du score cible sans le dépasser.',
      bj_r_target:      '<strong style="color:var(--gold);">Cible :</strong> Nombre aléatoire entre 21 et 80, différent à chaque manche.',
      bj_r_dealer:      '<strong style="color:var(--ok);">Désignation du croupier :</strong> Choisissez manuellement ou tirez au sort. Le croupier reste le même toute la partie.',
      bj_r_results_h:   '<strong style="color:var(--gold);">Résultats :</strong>',
      bj_r_r1:          'Score parfait (= cible) → +2€ (si croupier parfait aussi : égalité)',
      bj_r_r2:          'Meilleur que le croupier → +1€',
      bj_r_r3:          'Moins bon que le croupier → -1€',
      bj_r_r4:          'Dépasser la cible → score = 0',
      bj_r_dealer_perf: 'Si croupier parfait : tous les autres joueurs -2€.',
      // ── Règles Race 500 ───────────────────────────────────
      rc_rules_title:   '🏁 RÈGLES RACE',
      rc_r_obj:         '<strong style="color:var(--accent);">Objectif :</strong> Être le premier à atteindre exactement le score cible (300 ou 500).',
      rc_r_turn:        '<strong style="color:var(--ok);">Tour :</strong> 3 fléchettes. Points = numéro × multiplicateur.',
      rc_r_bust:        '<strong style="color:var(--danger);">Bust :</strong> Dépasser la cible annule tout le tour.',
      rc_r_steal:       '<strong style="color:var(--warn);">Vol :</strong> Atterrir sur le score exact d\'un adversaire lui vole des points (configurable) !',
      rc_r_out:         '<strong style="color:var(--dim);">OUT :</strong> 0 pt, compte comme une fléchette.',
      // ── Règles Bataille ───────────────────────────────────
      bt_rules_title:   '⚓ Règles — Bataille Navale',
      bt_r_princ_h:     '🎯 Principe',
      bt_r_princ_t:     'Chaque équipe <b>place secrètement ses bateaux</b> sur la cible. Les équipes tirent à tour de rôle pour <b>trouver et couler les bateaux adverses</b>.',
      bt_r_ships_h:     '🚢 Bateaux',
      bt_r_ships_t:     '<b>2 bateaux :</b> 1 ext., 1 libre.<br><b>3 bateaux :</b> 2 ext., 1 libre.<br><b>4 bateaux :</b> 2 ext., 2 libres.<br>Chaque bateau = 3 cases adjacentes.',
      bt_r_zones_h:     '🗺️ Zones de tir',
      bt_r_zones_t:     'Double / Simple ext. → anneau extérieur<br>Triple / Simple int. → anneau intérieur',
      bt_r_bull_h:      '🎯 Bull & Small Bull',
      bt_r_bull_t:      'Small Bull (25) → 2 cases aléatoires.<br>Bull (50) → 3 cases aléatoires.',
      bt_r_res_h:       '💥 Résolution',
      bt_r_res_t:       'TOUCHÉ si la case contient un bateau. COULÉ si toutes les cases sont touchées. RATÉ sinon.',
      bt_rules_win:     '🏆 Victoire',
      bt_rules_win_t:   'Première équipe à couler tous les bateaux adverses.',
      bt_rules_got:     'Compris !',

      // ── Setup / validation toasts ─────────────────────────────
      err_max_players:    '⚠️ Maximum {n} joueurs',
      err_min_players:    '⚠️ Minimum {n} joueurs',
      err_name_taken:     '⚠️ Ce pseudo existe déjà',
      err_add_1:          '⚠️ Ajoute au moins 1 joueur',
      err_add_2:          '⚠️ Ajoute au moins 2 joueurs',
      err_add_2_shuffle:  '⚠️ Ajoute au moins 2 joueurs pour mélanger',
      err_solo_max3:      '⚠️ Maximum 3 joueurs en solo',
      err_team_max2:      '⚠️ Maximum 2 joueurs par équipe',
      err_solo_min2:      '⚠️ Solo : 2 joueurs minimum requis',
      err_team_eq:        '⚠️ Mode Équipe : 2 joueurs par équipe requis',
      err_solo_max4:      '⚠️ Maximum 4 joueurs en solo',
      err_duel_max6:      '⚠️ Duel : max 6 joueurs',
      err_duel_min2:      '⚠️ Duel : minimum 2 joueurs',
      err_team_max6:      '⚠️ Équipe : max 6 joueurs (3v3)',
      err_team_min2:      '⚠️ Équipe : minimum 2 joueurs',
      err_team_same:      '⚠️ Équipe : même nombre de joueurs dans chaque équipe',
      err_team_max3:      '⚠️ Équipe : max 3 joueurs par équipe (3v3)',
      err_solo_mode:      '⚠️ Mode Solo : entre 2 et 4 joueurs requis',
      err_team_mode:      '⚠️ Mode Équipe : exactement 2 joueurs par équipe',
      err_solo1:          '⚠️ Maximum 1 joueur par équipe en solo',
      err_solo1b:         '⚠️ Mode Solo : 1 joueur par équipe maximum !',
      err_team_max_n:     '⚠️ Maximum {n} joueurs par équipe',
      err_name_dp:        '⚠️ Ce nom existe déjà !',
      err_target_pos:     'Les valeurs doivent être positives.',
      err_target_min:     'La cible min doit être strictement inférieure au max.',
      err_max6_bj:        '⚠️ Maximum 6 joueurs',
      err_pseudo_bj:      '⚠️ Pseudo déjà utilisé',
      err_dealer:         '⚠️ Désignez un croupier',
      err_targets:        '⚠️ Vérifiez les valeurs cible',
      err_min2_bj:        '⚠️ Minimum 2 joueurs',
      err_add2_rc:        'Ajoute au moins 2 joueurs',
      err_min2_rc:        'Minimum 2 joueurs',
      err_max6_rc:        'Maximum 6 joueurs',
      // ── Boutons communs ───────────────────────────────────────
      start_btn:          '🎯 DÉMARRER',
      cancel_shot:        '↩ Annuler',
      close_btn:          'Fermer',
      back_btn:           '← Retour',
      // ── Labels de tour / manche dynamiques ───────────────────
      round_n_of:         'MANCHE {r}/{t}',
      tour_n_of:          'TOUR {r}/{t}',
      turn_n:             'TOUR {n}',
      tour_label:         'Tour {n}',
      round_dart:         'TOUR {r} · FLÉCHETTE {d}/3',
      ckt_round_of:       'Tour : {r}/{t}',
      ckt_round:          'Tour : {r}',
      // ── 501 double-out modal ──────────────────────────────────
      x01_dout_title:     '🎯 Doubles tentés ce tour',
      x01_dout_sub_fin:   'Combien de doubles as-tu visé avant de finir ?',
      x01_dout_sub:       'Combien de doubles as-tu visé ce tour ?',
      // ── Territoire historique ─────────────────────────────────
      ter_bull_no_target: '💚 Bull vert (aucune cible)',
      ter_rbull_no_tgt:   '❤️ Bull rouge (aucune cible)',
      ter_out_of_play:    '→ zone {n} (hors jeu)',
      ter_out_ring:       '→ {n}{r} (hors jeu)',
      ter_no_shots:       'Aucun tir enregistré.',
      ter_no_zones:       'Aucune zone',
      // ── Territoire zones-drawer ───────────────────────────────
      ter_neutral_lbl:    '⬜ NEUTRES',
      // ── DartPong ────────────────────────────────────────────
      dp_streak_msg:      '{name} — 3 zones d\'affilée !',
      dp_bull_used:       '🎯 Bull (déjà utilisé)',
      dp_bull_announced:  '🎯 BULL annoncé !',
      dp_shot_cancelled:  'Tir annulé',
      dp_bull_q2:         'Avez-vous annoncé le bull avant de tirer ?',
      dp_party_fail:      '{name} a raté !',
      dp_no_players:      'Aucun joueur ajouté',
      // ── Shooter ───────────────────────────────────────────────
      sht_neutral_miss:   'Zone neutre',
      sht_dmg_toast:      '-{dmg} HP à {name}',
      sht_last_toast:     '{name} est tombé à 1 PV ! Choisis ta zone de survie :',
      sht_invuln_label:   '🛡️ Invulnérabilité :',
      sht_invuln_t1:      '• Bloque tous les dégâts jusqu\'au prochain tour',
      sht_last_t1:        '• À 1 HP : choisis 1 zone de survie',
      sht_last_t2:        '• Seule cette zone peut te toucher',
      // ── Blackjack ────────────────────────────────────────────
      bj_dealer_toast:    '🎩 {name} est croupier !',
      // ── Bataille ─────────────────────────────────────────────
      bt_placement_title: 'Équipe {t} — Placement secret',
      bt_placed_toast:    '{ship} placé !',
      bt_overlap:         'Superposition interdite !',
      bt_no_cells:        'Plus de cases disponibles !',
      bt_legend_title:    '📖 Légende',
      bt_leg_hit_desc:    'La fléchette a atteint une case contenant un bateau adverse',
      bt_leg_sink_desc:   'Les 3 cases du bateau ont toutes été touchées — bateau détruit',
      bt_leg_miss_desc:   'Aucun bateau adverse sur cette case (case vide, propre bateau ou doublon)',
      bt_leg_sunk_desc:   'Bateau hors jeu — toutes ses cases ont été touchées',
      bt_leg_sb_desc:     'Cercle vert extérieur — révèle 2 cases aléatoires non encore tirées',
      bt_leg_bull_desc:   'Cercle rouge intérieur — révèle 3 cases aléatoires non encore tirées',
      // ── Historique Shanghai ────────────────────────────
      shg_label_s:        'Simple',
      shg_label_d:        'Double',
      shg_label_t:        'Triple',
      // ── Historique DartPong ─────────────────────────
      dp_bull_aimed_used: 'vise le bull (d\'jà utilisé)',
      dp_bull_missed:     'rate le bull (non annoncé)',
      dp_hist_gage:       '→ OUT (gage accepté 🎭)',
      dp_hist_bull_sacr:  '🎯 BULL — sacrifie zone {n} ({type})',
      dp_hist_capture_h:  '❤️ capture {zone} + 🛡️',
      // ── Historique Shooter ───────────────────────────
      sht_own_zone_h:     '→ sa zone +{n} 💥',
      sht_no_bullets_h:   '→ pas de balles',
      sht_invuln_act_h:   '→ {name} invulnérable',
      sht_revive_hist:    '→ Ressuscite {name}',
      sht_heal_ally_h:    '→ +2 HP à {name}',

      // ── Commun ──────────────────────────────────────
      require_validate:   'Validation nécessaire',
      pp_manual_ph:       'Nom sans profil…',
      btn_validate:       'VALIDER',
      press_validate:     'Tour fini — Valider pour continuer',

      // ── Horloge ─────────────────────────────────────
      cl_title:           '🕐 HORLOGE',
      cl_ordre_lbl:       '📋 ORDRE',
      cl_ordre_asc:       '1 → 20',
      cl_ordre_desc:      '20 → 1',
      cl_ordre_rand:      'Aléatoire',
      cl_bull_lbl:        '🎯 BULL',
      cl_bull_none:       'Aucun',
      cl_bull_bull:       'Bull',
      cl_bull_bulleye:    'Bull + Eye',
      cl_hits_lbl:        '🎳 TIRS PAR NUMÉRO',
      cl_hits_1:          '1 fois',
      cl_hits_2:          '2 fois',
      cl_hits_3:          '3 fois',
      cl_skip_lbl:        '⚡ DOUBLE / TRIPLE',
      cl_skip_normal:     'Normal',
      cl_skip_skip:       'Saute 1–2 numéros',
      cl_skip_detail:     'Double = saute 1 numéro · Triple = saute 2 numéros',
      cl_skip_bull:       '(Bull ne peut pas être sauté)',
      cl_players:         '👥 JOUEURS (1-6)',
      cl_player_n:        'JOUEUR {n}/{t}',
      cl_target:          'CIBLE',
      cl_btn_simple:      'SIMPLE',
      cl_btn_double:      'DOUBLE',
      cl_btn_triple:      'TRIPLE',
      cl_btn_bull:        'BULL',
      cl_btn_bulleye:     'BULL EYE',
      cl_bull_pts:        '25 pts ✓',
      cl_bulleye_pts:     '50 pts ✓',
      cl_validate_lbl:    '✅ Validation nécessaire',
      cl_replay_lbl:      '🔁 3 réussites = Rejoue',
      cl_exploit_sub:     '3 réussites d\'affilée !',
      cl_miss:            'Raté',
      cl_undo:            'ANNULER',
      cl_validate:        'Valider',
      cl_hist:            '📜',
      cl_history:         '📜 HISTORIQUE',
      cl_next:            'Suivante :',
      cl_sub_advance1:    'Avance de 1',
      cl_sub_advance2:    'Avance de 2',
      cl_sub_advance3:    'Avance de 3',
      cl_sub_valid:       '✓ valide',
      cl_sub_hit1:        '+1 hit',
      cl_sub_hit2:        '+2 hits',
      cl_sub_hit3:        '+3 hits',
      cl_wins:            'GAGNE !',
      cl_finished:        'A complété tout l\'horloge !\nDernière cible :',
      cl_bull_note:       '(Bull ne peut pas être sauté)',
      cl_validate_toast:  'Tour fini — Valider pour continuer',
      cl_not_bulleye:     'pas BullEye',
      cl_replay_msg:      'REJOUE ! (3 réussites)',
      cl_skip_msg:        'saute',
      cl_pct_clock:       '% horloge',
      cl_miss_hist:       'Raté',
      cl_rules_title:     '📖 RÈGLES — HORLOGE',

      // ── Welcome popup ─────────────────────────────────────
      welcome_title:      'Bienvenue sur DartVault !',
      welcome_step1_title:'Créez vos profils',
      welcome_step1_desc: 'En quelques secondes ajoutez votre profil et celui de vos amis, suivez ensuite les classements pour chaque jeu !',
      welcome_step2_title:'Lancez des parties rapides',
      welcome_step2_desc: 'Chaque jeu est facile à prendre en main, du débutant au confirmé.',
      welcome_step3_title:'Des règles simples',
      welcome_step3_desc: 'Accessibles d\'un tap sur chaque jeu, laissez-vous guider !',
      welcome_ok:         'C\'EST PARTI !',
      welcome_dismiss:    'Ne plus afficher ce message',
    },

    en: {
      // ── Header ──────────────────────────────────────────────
      menu:      '← Menu',
      back:      '← Back',
      rules_btn: 'ℹ️',
      theme: 'Theme', theme_dark: '🌙 Dark', theme_light: '☀️ Light', theme_colored: '🎨 Coloured',
      vibrations: 'Vibrations', sounds: 'Sounds', announcer: 'Announcer',
      pp_title: '👤 CHOOSE A PROFILE',
      pp_empty: 'No profiles saved yet.\nCreate one from the main menu!',
      pp_cancel: 'Cancel',
      pp_manage: '＋ Manage profiles',
      pp_all_used: 'All profiles are already in the game.',

      // ── Setup commun ────────────────────────────────────────
      start:          'START',
      shuffle:        '🔀 Shuffle',
      player_ph:      'Player name',
      add_player:     '+ Add',
      players_label:  '👥 Players',
      mode_label:     '🎮 Mode',
      format_label:   '🏆 Format',
      rounds_label:   'ROUNDS',
      sets_label:     'SETS',
      sets_sub:       '(3 rounds/set)',
      diff_label:     '⚔️ Difficulty',
      easy_btn:       '😊 Easy',
      normal_btn:     '⚔️ Normal',

      solo_2_3:  'Solo (2-3)',
      solo_2_4:  'Solo (2-4)',
      solo_2_6:  'Solo (2-6)',
      solo_2:    'Solo (2)',
      team_2_4:  'Team (2-4)',
      team_2_6:  'Team (2-6)',

      team_blue:    '🔵 BLUE TEAM',
      team_yellow:  '🟡 YELLOW TEAM',
      team_purple:  '🟣 PURPLE TEAM',
      player_blue:  '🔵 BLUE PLAYER',
      player_yellow:'🟡 YELLOW PLAYER',
      player_purple:'🟣 PURPLE PLAYER',
      blue:     'BLUE',
      yellow:   'YELLOW',
      purple:   'PURPLE',
      bleue:    'Blue',
      jaune:    'Yellow',
      violette: 'Purple',
      team_a_full:  'BLUE TEAM 🔵',
      team_b_full:  'YELLOW TEAM 🟡',
      player_c_full:'PURPLE PLAYER 🟣',

      undo:        'UNDO',
      undo_cap:    'UNDO',
      undo_last:   '↩ Undo last shot',
      validate:    'VALIDATE',
      out:         'OUT',
      bull:        'BULL',
      history:     '📜 History',
      history_cap: '📜 HISTORY',
      quick_sel:   'Quick select',
      legend_btn:  '📖 Legend',
      legend_cap:  '📖 LEGEND',
      zones_btn:   '🗺️ Zones',
      zones_cap:   '🗺️ ZONES',
      single:      'Single',
      double:      'Double',
      triple:      'Triple',
      zone_lbl:    'Zone',
      center:      'Centre',
      round_lbl:   'Turn',
      player_col:  'Player',

      quit_title:  '⚠️ Quit game?',
      quit_short:  '⚠️ Quit?',
      quit_sub:    'The current game will be lost.',
      quit_yes:    '🚪 Quit',
      quit_no:     '▶️ Continue',
      continue_btn:'Continue',

      rematch:      '🔄 Rematch',
      config:       '⚙️ Settings',
      cancel:       'Cancel',
      close:        'Close',
      rules_ok:     'OK',
      rules_hide:   'Hide on launch',
      end_title:    'END',
      results:      'Results',
      next_round:   '➡️ Next round',
      hist_rounds:  '📋 Rounds history',
      hist_shots:   '📋 Shots history',
      congrats:     'CONGRATULATIONS!',

      x01_mode:       '🎯 Game mode',
      x01_entry:      '📝 Input',
      x01_total:      'Total',
      x01_endgame:    '🏁 End game',
      x01_doubleout:  'Double Out',
      x01_simpleout:  'Single Out',
      x01_dblindblout:'D. In / D. Out',
      x01_di_q:       'Double In?',
      x01_di_sub:     'Did you hit a double this turn?',
      x01_di_yes:     '✅ Yes, double done',
      x01_di_no:      '🚫 No double hit',
      x01_di_cancel:  '↩ Cancel input',
      x01_di_miss:    '🎯 Double In missed',
      x01_format:     '🏆 Format',
      x01_stats_chk:  '📊 Track Double Out %',
      x01_players:    '👥 Players (1-6)',
      x01_avg:        'AVG',
      x01_best:       'BEST',
      x01_chip_darts: 'DARTS',
      x01_darts:      'DARTS',
      x01_prev:       'PREV. TURN',
      x01_finish:     '💡 FINISH :',
      x01_dart1:      'DART 1/3',
      x01_single_x:   'SINGLE ×1',
      x01_double_x:   'DOUBLE ×2',
      x01_triple_x:   'TRIPLE ×3',
      x01_25bull:     '25/Bull',
      x01_stats_cap:  '📊 STATISTICS',
      x01_checkout:   '🎯 CHECKOUT!',
      x01_checkout_q: 'Confirm the finish?',
      x01_checkout_y: '✅ Yes, won!',
      x01_checkout_n: '❌ No, cancel',
      x01_dbl_tries:  '🎯 Double Out Attempts',
      x01_dbl_q:      'How many doubles did you aim for this turn?',
      x01_bigfish:    'BIG FISH',
      x01_bigfish_sub:'Finish 170 — The maximum possible!',
      x01_bigfish_btn:'Amazing!',
      x01_menu_btn:   '🏠 Menu',
      x01_no_history: 'No throws yet.',
      x01_legs_label: 'legs',
      x01_throws_hist:'THROW HISTORY',
      x01_hist_title: 'HISTORY',
      x01_rounds_dlg: 'Number of rounds',
      x01_rules_title:'🎯 X01 RULES',
      x01_rules_obj:  'Goal:',
      x01_rules_obj_t:'Count down your score to exactly 0.',
      x01_rules_bust: 'Bust:',
      x01_rules_dbl:  'Double Out:',
      x01_rules_dbl_t:'The last dart must hit a double (D1–D20 or Bull 50).',
      x01_rules_spl:  'Single Out:',
      x01_rules_spl_t:'You can finish on any zone.',
      x01_rules_max:  'Max score per visit:',
      x01_rules_fin:  'Finish:',
      x01_rules_fin_t:'Suggestions shown from 170 pts or less.',

      ckt_mode:       '🎯 Game mode',
      ckt_std:        'Standard',
      ckt_cut:        'Cut-throat',
      ckt_noscore:    'No Score',
      ckt_random:     'Random zones',
      ckt_tours:      '⏱️ Turns per round',
      ckt_players:    '👥 Players (2-6)',
      ckt_players_ns: '👥 Players (1-6)',
      ckt_rounds_dlg: 'Number of rounds',
      ckt_continue:   '▶ Continue',
      ckt_end:        '🏆 GAME OVER',
      ckt_hist:       '📜 HISTORY',
      ckt_rules_title:'🦗 Cricket Rules',
      ckt_rules_nums: 'Cricket Numbers',
      ckt_rules_bull: 'BULL',
      ckt_rules_marks:'Marks',
      ckt_rules_m_sub:'3 darts in a number = closed.',
      ckt_rules_pts:  'Points',
      ckt_rules_win:  'Win — Standard',
      ckt_rules_win_t:'Close all numbers with the highest score.',
      ckt_rules_cut:  '⚔️ Cut-throat',
      ckt_rules_cut_t:'fewest points',
      ckt_rules_cut_t2:'at closing wins.',
      ckt_rules_ns:   '🚫 No Score',
      ckt_rules_ns_t: 'No points. First player to close all numbers wins. Pure speed!',
      ckt_rules_btns: 'Buttons',
      ckt_rules_out:  'OUT',
      ckt_rules_out_t:'= dart outside cricket, uses a dart.',
      ckt_rules_rnds: 'Rounds',
      ckt_rules_wh:   '🐎 White Horse',
      ckt_rules_wh_t: '3 Triples in the same turn on completely virgin zones',
      ckt_rules_wh_t2:'(no player has touched these zones yet) triggers the legendary White Horse!',
      ckt_whitehorse: 'WHITE HORSE',
      ckt_wh_sub:     '3 Triples on virgin zones in the same turn — Legendary!',
      ckt_wh_sub2:    'Impressive!',
      ckt_leg_abbr:   'L',
      ckt_legs_label: 'legs',
      ckt_set_abbr:   'S',
      ckt_out_lbl:    'Miss',
      ckt_adv:        'opp',

      shg_rounds:     '🎯 ROUNDS',
      shg_mode_lbl:   '🎯 GAME MODE',
      shg_mode_std:   'Standard',
      shg_mode_rnd:   'Random',
      shg_sectors_lbl:'🔺 NUMBER OF SECTORS',
      shg_players:    '👥 Players (2-6)',
      shg_round_lbl:  'ROUND {r}/{t}',
      shg_round_abbr: 'R',
      shg_target:     'TARGET',
      shg_single:     'SINGLE',
      shg_s_pts:      '+1 pts',
      shg_double:     'DOUBLE',
      shg_d_pts:      '+2 pts',
      shg_triple:     'TRIPLE',
      shg_t_pts:      '+3 pts',
      shg_hist:       '📜 HISTORY',
      shg_event:      'SHANGHAI!',
      shg_event_sub:  'Single + Double + Triple of',
      shg_event_sub2: '— Legendary!',
      shg_confirm:    '🎆 Confirm Shanghai!',
      shg_cancel_shot:'↩ Cancel shot',
      shg_recap:      'Summary',
      shg_rules_title:'🎯 SHANGHAI RULES',
      shg_rules_obj:  'Goal:',
      shg_rules_obj_t:'Score the most points in 7 rounds. Each round has a target (1 to 7 in Standard mode, or random in Random mode).',
      shg_rules_shg:  'Shanghai:',
      shg_rules_shg_t:'Hit Single + Double + Triple of the same target in one turn = instant win!',
      shg_rules_out:  'MISS:',
      shg_rules_out_t:'Dart outside target, 0 points.',
      shg_rules_end:  'End:',
      shg_rules_end_t:'After all rounds, player with most points wins.',

      ter_zones:      '🎯 Number of zones',
      ter_rounds:     '⏱️ Number of rounds',
      ter_mode:       '🎮 Game mode',
      ter_solo:       'Solo (2-3)',
      ter_team:       'Team (2-6)',
      ter_diff:       '⚔️ Difficulty',
      ter_players:    '👥 Players (2-3)',
      ter_round_lbl:  'ROUND {r}/{t}',
      ter_bull_title: '🎯 Bull Zone',
      ter_bull_q:     'Which zone did you hit?',
      ter_small_bull: '🟢 Small Bull (25)',
      ter_bull50:     '🔴 Bull (50)',
      ter_mult_zone:  'Zone',
      ter_rules_title:'🏰 GAME RULES',
      ter_rules_obj:  '🎯 Goal',
      ter_rules_obj_t:'Capture as many zones as possible. Win by controlling all zones or holding the most at the end of rounds.',
      ter_rules_sd:   'Single / Double',
      ter_rules_sd_t: '→ Captures neutral zone or neutralises enemy zone',
      ter_rules_sd_t2:'→ Direct capture of an enemy zone without shield',
      ter_rules_tn:   'Triple on neutral zone',
      ter_rules_tn_t: '→ Capture + 🛡️ shield added',
      ter_rules_ty:   'Triple on your zone',
      ter_rules_ty_t: '→ Adds a 🛡️ shield',
      ter_rules_sh:   '🛡️ Shield',
      ter_rules_sh_t: 'Protects the zone from a single/double attack',
      ter_rules_bull: '🔄 Turn',
      ter_rules_bull_t:'3 darts per player, then next player. New round when all players have played.',

      dp_zones:       '🎯 Area',
      dp_diff:        '⚔️ Difficulty',
      dp_mode:        '🎮 Game mode',
      dp_solo:        'Solo (2-6)',
      dp_team:        'Team (2-6)',
      dp_options:     '🎉 OPTIONS',
      dp_party:       'Party mode',
      dp_players:     '👥 Players (2-6)',
      dp_bull_title:  '🎯 Announce BULL?',
      dp_bull_q:      'Did you announce the bull before throwing?',
      dp_bull_yes:    '✅ YES',
      dp_bull_no:     '❌ NO',
      dp_confirm_t:   'Double 18?',
      dp_confirm_q:   'Confirm this shot?',
      dp_confirm_y:   '✅ Yes',
      dp_confirm_n:   '❌ No',
      dp_exploit:     '🔥 EXPLOIT!',
      dp_exploit_sub: '3 zones eliminated in a row!',
      dp_bonus:       '⚡ BONUS: REPLAY A FULL TURN ⚡',
      dp_replay:      'OK — REPLAY',
      dp_party_title: '🎉 PARTY MODE!',
      dp_party_miss:  'You missed!',
      dp_party_drink: '🍺 Take a sip',
      dp_party_lose:  '⏭️ Lose a dart',
      dp_zones_left:  '🗺️ REMAINING ZONES',
      dp_rules_title: '🍺 DARTPONG RULES',
      dp_rules_obj:   'Goal:',
      dp_rules_obj_t: 'Eliminate all your zones before your opponent.',
      dp_rules_zones: 'Zones:',
      dp_rules_str:   '🔥 Streak x3:',
      dp_rules_str_t: 'Eliminate 3 zones in a row = replay a full turn!',
      dp_rules_bull:  '🎯 Bull (announced):',
      dp_rules_bull_t:'Eliminates 2 random zones of your team. Must be announced before throwing, usable once per team.',
      dp_rules_party: '🎉 Party Mode:',
      dp_rules_party_t:'On a neutral zone (opponent or out-of-zone), choose between a dare or losing your next dart.',
      dp_rules_3d:    '3 darts',
      dp_rules_3d_t:  'per player per turn.',

      sht_hp:         '❤️ HIT POINTS',
      sht_diff:       '⚔️ DIFFICULTY',
      sht_mode:       '🎮 Game mode',
      sht_solo:       'Solo (2-4)',
      sht_team:       'Team (2-4)',
      sht_players:    '👥 Players (2-4)',
      sht_turn:       'TURN 1',
      sht_last_title: '⚠️ LAST STAND',
      sht_last_sub:   'You are down to 1 HP! Choose your survival zone:',
      sht_undo_last:  '↩ Undo last shot',
      sht_hist:       '📜 HISTORY',
      sht_rules_title:'💥 BATTLE ROYAL RULES',
      sht_rules_obj:  '🎯 Goal:',
      sht_rules_obj_t:'Be the last survivor (or team)',
      sht_rules_dead: 'Drops to 0 → eliminated',
      sht_rules_ammo: '💥 Ammo:',
      sht_rules_a_t:  'Required to attack',
      sht_rules_bul1: '💚 Green bull:',
      sht_rules_bul1t:'+2 HP or heal/revive',
      sht_rules_bul2: '❤️ Red bull:',
      sht_rules_bul2t:'Removes invulnerabilities + bonus choice',
      sht_rules_inv:  '🛡️ Invulnerability:',
      sht_rules_inv_t:'Ignore damage (1 turn)',
      sht_rules_ls:   '⚠️ Last Stand (easy mode):',
      sht_rules_ls_t: 'At 1 HP, choose 1 survival zone',
      sht_leg_zones:  '🎯 Zones:',
      sht_leg_own:    'Your zone',
      sht_leg_own_t:  ': Reload +1/2/3 💥 (single/triple/double)',
      sht_leg_enemy:  'Enemy zone',
      sht_leg_enemy_t:': -1 ammo, deals 1/2/3 damage',
      sht_leg_neutral:'Neutral zone',
      sht_leg_neut_t: ': Miss, -1 ammo',
      sht_leg_bulls:  '🐂 Bulls:',
      sht_leg_grbull: '💚 Green',
      sht_leg_grb_t:  ': +2 HP or revive ally',
      sht_leg_rdbull: '❤️ Red',
      sht_leg_rdb_t:  ': Remove invulnerabilities, then +2 HP or immunity',

      bj_rounds:      '🎯 ROUNDS',
      bj_min:         '📉 MIN',
      bj_max:         '📈 MAX',
      bj_players:     '👥 Players (2-6)',
      bj_rnd_dealer:  '🎲 Random dealer',
      bj_dealer_hint: '🎩 Tap',
      bj_dealer_btn:  'Dealer',
      bj_dealer_hint2:'to assign manually, or use the random button.',
      bj_target:      'Target score',
      bj_round_lbl:   'ROUND {r}/{t}',
      bj_round_label: 'Round {r}/{t}',
      bj_players_col: 'Players',
      bj_dealer_cap:  '🎩 DEALER',
      bj_bj_title:    'BLACKDART!',
      bj_bj_sub:      'Perfect score — exactly the target! 🎯',
      bj_bj_sub2:     'Incredible!',
      bj_hist_rounds: '📋 Rounds history',
      bj_rules_title: '🎰 BLACKDART RULES',
      bj_rules_obj:   'Goal:',
      bj_rules_obj_t: 'Get as close to the target score as possible without exceeding it.',
      bj_rules_tgt:   'Target:',
      bj_rules_tgt_t: 'Random number between 21 and 80, different each round.',
      bj_rules_dealer:'Dealer assignment:',
      bj_rules_dlr_t: 'Choose manually or draw lots. The dealer stays the same for the whole game.',
      bj_rules_res:   'Results:',
      bj_rules_r1:    'Perfect score (= target) → +2€ (if dealer also perfect: tie)',
      bj_rules_r2:    'Better than dealer → +1€',
      bj_rules_r3:    'Worse than dealer → -1€',
      bj_rules_r4:    'Exceeding the target → score = 0',
      bj_rules_r5:    'If dealer is perfect: all other players -2€.',

      rc_target:      '🏁 Target score',
      rc_steal_cfg:   '🎯 Steal amount',
      rc_steal_off:   'None',
      rc_players:     '👥 Players (2-6)',
      rc_turn:        'TURN 1 · DART 1/3',
      rc_single_x:    'SINGLE ×1',
      rc_double_x:    'DOUBLE ×2',
      rc_triple_x:    'TRIPLE ×3',
      rc_25bull:      '25/Bull',
      rc_bust_title:  '💥 BUST!',
      rc_bust_sub:    'Dart cancelled.',
      rc_end_title:   '🏁 FINISH!',
      rc_hist:        '📋 Shots history',
      rc_rules_title: '🏁 RACE RULES',
      rc_rules_obj:   'Goal:',
      rc_rules_obj_t: 'Be the first to reach exactly the target score (300 or 500).',
      rc_rules_turn:  'Turn:',
      rc_rules_turn_t:'3 darts. Points = number × multiplier.',
      rc_rules_bust:  'Bust:',
      rc_rules_bust_t:'Exceeding the target cancels the entire turn.',
      rc_rules_steal: 'Steal:',
      rc_rules_steal_t:"Landing on an opponent's exact score steals points from them (configurable)!",
      rc_rules_out:   'MISS:',
      rc_rules_out_t: '0 pts, counts as a dart.',

      bt_ships:         '🚢 Number of ships',
      bt_mode:          '🎮 Game mode',
      bt_solo:          'Solo (2)',
      bt_team:          'Team (2-6)',
      bt_players:       '👥 Players (2)',
      bt_team_blue:     '🔵 BLUE TEAM',
      bt_team_yellow:   '🟡 YELLOW TEAM',
      bt_handoff_title: 'Pass the phone',
      bt_handoff_sub:   "It's the team's turn to secretly place their ships.",
      bt_handoff_btn:   "Let's go!",
      bt_attack_title:  '📱 Pass the phone',
      bt_attack_sub:    "It's the team's turn to attack!",
      bt_attack_btn:    '⚔️ Ready!',
      bt_place_hint1:   'Tap a zone to place a ship (3 adjacent squares)',
      bt_place_hint2:   'Tap the target to choose the centre square of the ship',
      bt_confirm_title: '🎯 Confirm shot',
      bt_confirm_q:     'Confirm this shot?',
      bt_confirm_zone:  'Zone: —',
      bt_confirm_yes:   '✅ Yes, that\'s it',
      bt_confirm_no:    '↩ No, cancel',
      bt_bull_title:    '🎯 Bull Zone',
      bt_bull_q:        'Which zone did you hit?',
      bt_small_bull:    '🟢 Small Bull (25)',
      bt_bull50:        '🔴 Bull (50)',
      bt_win:           '🏆 VICTORY!',
      bt_quit:          '⚠️ Quit?',
      bt_blue_lbl:      '⚓ BLUE',
      bt_yellow_lbl:    '⚓ YELLOW',
      bt_blue_team:     'Blue',
      bt_yellow_team:   'Yellow',
      bt_blue_team_cap: 'BLUE',
      bt_yellow_team_cap:'YELLOW',
      bt_place_title:   'Blue Team — Placement',
      bt_hist:          '📜 HISTORY',
      bt_rules_title:   '⚓ Rules — Battleship',
      bt_rules_princ:   '🎯 Principle',
      bt_rules_ships:   '🚢 Ships',
      bt_rules_zones:   '🗺️ Shooting zones',
      bt_rules_bull:    '🎯 Bull & Small Bull',
      bt_rules_res:     '💥 Resolution',
      bt_rules_win:     '🏆 Victory',
      bt_rules_win_t:   'First team to sink all enemy ships.',
      bt_rules_got:     'Got it!',
      bt_leg_hit:       'HIT',
      bt_leg_hit_t:     'The dart reached a square containing an enemy ship',
      bt_leg_sink:      'SUNK',
      bt_leg_sink_t:    'All 3 squares of the ship have been hit — ship destroyed',
      bt_leg_miss:      'MISS',
      bt_leg_miss_t:    'No enemy ship on this square (empty, own ship or duplicate)',
      bt_leg_intact:    'SHIP INTACT',
      bt_leg_intact_t:  'Ship still in play in the fleet',
      bt_leg_sunk:      'SHIP SUNK',
      bt_leg_sunk_t:    'Ship out of play — all its squares have been hit',
      bt_leg_sb:        'SMALL BULL (25)',
      bt_leg_sb_t:      'Outer green circle — reveals 2 random squares not yet fired upon',
      bt_leg_bull:      'BULL (50)',
      bt_leg_bull_t:    'Inner red circle — reveals 3 random squares not yet fired upon',

      // ── Clés dynamiques ajoutées ─────────────────────────────
      x01_impossible:   'Impossible score',
      x01_stat_busts:   'Busts',
      x01_bust_hint:    '💥 BUST — turn cancelled',
      x01_bust_one:     '💥 BUST — 1 left (impossible)',
      x01_remaining:    'Left: ',
      x01_hit_double:   'hit a double?',
      x01_finishes:     'finishes the game!',
      x01_score_colon:  'Score: ',
      x01_bust_toast:   '💥 BUST! Score unchanged.',
      x01_stat_moyenne: 'Average',
      x01_stat_best:    'Best visit',
      x01_stat_dout:    'Double Out %',
      x01_stat_darts:   'Darts',
      x01_stat_remaining:'Remaining',
      x01_no_shots:     'No throws recorded',
      x01_sets_dlg:     'Number of sets',
      ckt_draw:         'DRAW!',
      ckt_wins_set:     'wins the set!',
      ckt_wins_leg:     'wins the leg!',
      ckt_sets_colon:   'Sets: ',
      ckt_legs_in_set:  'Legs in set: ',
      shg_wins:         'wins the game!',
      shg_draw:         '🤝 TIE!',
      shg_wins_short:   'wins!',
      ter_victory:      'VICTORY!',
      ter_total_control:'Full territory control!',
      ter_draw:         'DRAW!',
      ter_hist_captured:'captured',
      ter_hist_captured_shield:'captured + 🛡️',
      ter_hist_shield_added:'+ 🛡️',
      ter_hist_allied:  'allied (nothing)',
      ter_hist_shield_neutral:'🛡️ broken + neutralised',
      ter_hist_shield_broken:'🛡️ broken',
      ter_hist_direct:  'direct capture',
      ter_hist_neutral: 'neutralised',
      dp_sector:        'Sector',
      dp_simple_ext:    'Single outer',
      dp_simple_int:    'Single inner',
      dp_not_started:   'Game not started',
      dp_all_eliminated:'All eliminated!',
      sht_allied_zone:  'allied zone',
      sht_invuln_toast: 'Invulnerable!',
      sht_eliminated:   'ELIMINATED',
      sht_last_active:  'Last Stand active',
      sht_last_toast:   'Last Stand!',
      sht_invuln_hist:  'Invulnerable (removes others)',
      sht_invuln_hist_suffix:'(removes others)',
      sht_invuln_expire:'Invuln expires',
      sht_invuln_expire_dead:'Invuln expires (giver eliminated)',
      sht_invuln_label: 'Invulnerability',
      sht_invuln_me:    'Invuln for me',
      sht_invuln_for:   'Invuln for',
      sht_revive:       'Revive',
      sht_to_1hp:       'to 1 HP',
      sht_to_2hp:       'to 2 HP',
      sht_last_zone:    'Last Stand zone',
      sht_stat_bullets: '💥 Ammo',
      sht_stat_damage:  '🗡️ Damage',
      bj_below_target:  'below target',
      bj_busted:        'busted!',
      bj_over_hint:     'Over — score = 0',
      bj_score_colon:   'Score:',
      bj_balance_colon: 'Balance:',
      bj_round_lbl2:    'ROUND {r}/{t}',
      rc_steal_lbl:     'STEAL',
      rc_remaining:     'Left: {n}',
      rc_steal_bust_lbl:'STEAL BUST',
      rc_steal_toast:   '💥 {p} steals {pts} pts from {o}!',
      rc_exceeds:       'exceeds',
      rc_exceeds_steal: 'exceeds after steal',
      rc_cancelled:     'Turn cancelled — back to',
      rc_no_shots:      'No shots played',
      rc_stat_stolen:   'Stolen:',
      rc_stat_lost:     'Lost:',
      rc_pts_ahead:     'pts ahead',
      rc_darts_abbr:    'drt',
      bt_placement_done:'Placement done',
      bt_pass_phone_team:'Pass the phone to Team {tn}.',
      bt_place_ships:   'Place your {n} ships secretly.',
      bt_current_ship:  'Current ship',
      bt_to_place:      'TO PLACE',
      bt_ships_placed:  'ships placed',
      bt_fleet_label:   'FLEET',
      bt_ring:          'ring',
      bt_ring_ext:      'outer',
      bt_ring_int:      'inner',
      bt_ring_any:      'outer or inner',
      bt_ring_ext_full: 'Outer ring',
      bt_ring_int_full: 'Inner ring',
      bt_leg_intact_desc: 'Ship still in play',
      bt_hit:           '💥 HIT!',
      bt_sunk:          '💀 SUNK!',
      bt_miss:          '💨 MISS',
      bt_dup_shot:      '💨 Already fired — Miss!',
      bt_out_miss:      'miss',
      ter_header_title: '🏰 TERRITORY',
      bat_header_title: '⚓ BATTLESHIP',
      bt_ship_ring_error:'This ship must be on the',
      bt_team_wins:     'Team {team} wins!',
      bt_ship_carrier:   '⚓ Carrier',
      bt_ship_sub:       '🤿 Submarine',
      bt_ship_free_any:  '🚢 Free ship',
      bt_ship_battleship:'🛳 Battleship',
      bt_ship_cruiser:   '⛵ Cruiser',
      bt_ship_libre:     '🚢 Free',
      bt_ship_libre1:    '🚢 Free 1',
      bt_ship_libre2:    '🚢 Free 2',
      mode_label:       '🎮 Game Mode',
      zone_lbl:         'Area',
      ter_mode:         '🎮 Game mode',
      dp_mode:          '🎮 Game mode',

      // ── Nouvelles clés dynamiques round 2 ───────────────────
      x01_dart1_info:   'DART 1/3',
      x01_dart_n:       'DART {n}/3',
      x01_turn_done:    '✅ Turn done',
      x01_3darts_validate: 'Turn done — Validate to continue',
      x01_set_won:      'Set won!',
      x01_leg_won:      'Leg won!',
      x01_match_score:  'MATCH SCORE',
      x01_sets_to_win:  'set(s) to win',
      x01_legs_to_win:  'leg(s) to win',
      x01_sets_lbl:     'sets',
      x01_legs_lbl:     'legs',
      x01_next_set:     '➡️ Next set',
      x01_wins_match:   'wins the match!',
      x01_avg_lbl:      'Avg.',
      x01_per_dart:     'Per dart',
      x01_not_aimed:    'Not aimed',
      x01_attempt:      'attempt',
      x01_attempts:     'attempts',
      ckt_no_winner:    'Nobody wins this leg.',
      ckt_legs_simple:  'Legs: ',
      ter_teams_lbl:    'Teams',
      dp_dart_lost:     'Dart lost',
      dp_per_player:    'PER PLAYER',
      bj_end_title:     'GAME OVER',
      bj_wins_with:     'wins with',
      bj_no_rounds:     'No rounds played',
      bj_hist_round_lbl:'ROUND {r}',
      rc_turn_info:     'TURN {t} · DART {d}/3',
      rc_wins:          'wins the race!',
      rc_leading:       '1st',
      rc_to_finish:     'to finish',
      bt_attack_turn:   'Team {team} — your turn to attack! (3 darts)',

      // ── Rules 501 ─────────────────────────────────────────
      x01_rules_title:  '🎯 X01 RULES',
      x01_r_obj:        '<strong style="color:var(--accent);">Goal:</strong> Count your score down to exactly 0.',
      x01_r_bust:       '<strong style="color:var(--accent);">Bust:</strong> If the score goes below 0 or reaches 1 (Double Out), the turn is cancelled and the score returns to its previous value.',
      x01_r_dout:       '<strong style="color:var(--ok);">Double Out:</strong> The last dart must hit a double (D1–D20 or Bull 50).',
      x01_r_sout:       '<strong style="color:var(--warn);">Single Out:</strong> You can finish on any segment.',
      x01_r_max:        '<strong style="color:var(--accent);">Max visit score:</strong> 180 (T20 + T20 + T20).',
      x01_r_finish:     '<strong style="color:var(--accent);">Finish:</strong> Checkout suggestions shown at 170 pts or below.',
      // ── Rules Cricket ─────────────────────────────────────
      ckt_rules_title:  '🦗 Cricket Rules',
      ckt_rules_nums:   'Cricket Numbers',
      ckt_r_nums_t:     '15, 16, 17, 18, 19, 20 and <strong>BULL</strong>.',
      ckt_rules_marks:  'Marks',
      ckt_r_marks_t:    '3 darts on a number = closed.<br><strong>/</strong> = 1 mark &nbsp;·&nbsp; <strong>X</strong> = 2 marks &nbsp;·&nbsp; <strong>✦</strong> = closed',
      ckt_rules_pts:    'Points',
      ckt_r_pts_t:      'Once a number is closed, each additional mark scores points until opponents close it too.',
      ckt_rules_win:    'Win — Standard',
      ckt_rules_win_t:  'Close all numbers with the most points.',
      ckt_r_cutthroat:  'Your points go to opponents! When you score on a closed number, opponents who haven\'t closed it yet receive the points. The player with the <strong>fewest points</strong> when all numbers are closed wins.',
      ckt_r_noscore:    'No points. The first player to close all numbers wins. Pure speed!',
      ckt_r_btns_h:     'Buttons',
      ckt_r_btns_t:     '<strong>S ×1</strong> = Single &nbsp;·&nbsp; <strong>D ×2</strong> = Double &nbsp;·&nbsp; <strong>T ×3</strong> = Triple<br><strong>OUT</strong> = dart outside cricket, uses up a dart.',
      ckt_r_legs_h:     'Legs',
      ckt_r_legs_t:     'In infinite mode, the game ends when a player closes all numbers. In limited legs (10, 15, 20), the game stops at the last leg and the final standings determine the winner.',
      ckt_r_wh:         'Hitting <strong>3 Triples in the same turn on completely untouched numbers</strong> (no player has scored on them yet) triggers the legendary White Horse!',
      // ── Rules Shanghai ────────────────────────────────────
      shg_rules_title:  '🎯 SHANGHAI RULES',
      shg_r_obj:        '<strong style="color:var(--accent);">Goal:</strong> Score the most points in 7 rounds. Each round has a target (1 to 7 in Standard mode, or random in Random mode).',
      shg_r_scoring:    '<strong style="color:var(--ok);">Single</strong> = value × 1 &nbsp;|&nbsp; <strong style="color:var(--ok);">Double</strong> = value × 2 &nbsp;|&nbsp; <strong style="color:var(--warn);">Triple</strong> = value × 3',
      shg_r_shanghai:   '<strong style="color:var(--warn);">Shanghai:</strong> Hit Single + Double + Triple on the same target in one turn = instant win!',
      shg_r_out:        '<strong style="color:var(--dim);">OUT:</strong> Dart misses the target, 0 points.',
      shg_r_end:        '<strong>End:</strong> After all rounds, the player with the most points wins.',
      // ── Rules Territoire ──────────────────────────────────
      ter_rules_title:  '🏰 GAME RULES',
      ter_r_obj_h:      '🎯 Goal',
      ter_r_obj_t:      'Capture as many zones as possible. Win by controlling all zones or holding the most at the end of the rounds.',
      ter_r_zones_h:    '🗺️ Zones',
      ter_r_z1:         '<strong>Single / Double</strong> → Capture a neutral zone or neutralise an enemy zone',
      ter_r_z2:         '<strong>Triple</strong> → Direct capture of an enemy zone with no shield',
      ter_r_z3:         '<strong>Triple on neutral zone</strong> → Capture + 🛡️ shield added',
      ter_r_z4:         '<strong>Triple on your zone</strong> → Adds a 🛡️ shield',
      ter_r_shield_h:   '🛡️ Shield',
      ter_r_sh1:        'Protects the zone from a single/double attack',
      ter_r_sh2:        'A single/double breaks the shield without capturing',
      ter_r_sh3:        'A triple breaks the shield AND neutralises the zone',
      ter_r_bull25_h:   '💚 Green Bull (25 pts)',
      ter_r_bull25_t:   'Neutralises 2 random enemy zones. If a zone has a shield, it is broken first.',
      ter_r_bull50_h:   "❤️ Red Bull (Bull's Eye)",
      ter_r_bull50_t:   'Captures a random enemy zone + adds a 🛡️ shield.',
      ter_r_turn_h:     '🔄 Turn order',
      ter_r_turn_t:     '3 darts per player, then pass to the next. New round when all players have thrown.',
      // ── Rules DartPong ───────────────────────────────────
      dp_rules_title:   '🍺 DARTPONG RULES',
      dp_r_obj:         '<strong style="color:var(--accent);">Goal:</strong> Eliminate all your zones before your opponent.',
      dp_r_zones:       '<strong style="color:var(--ok);">Zones:</strong> Each team has N random zones (singles, doubles or triples). To eliminate a zone, you must hit it exactly.',
      dp_r_streak:      '<strong style="color:#FFD700;">🔥 Streak x3:</strong> Eliminate 3 zones in a row = play a full extra turn!',
      dp_r_bull:        '<strong style="color:#FFD700;">🎯 Bull (called):</strong> Eliminates 2 random zones for your team. Must be called before throwing, usable once per team.',
      dp_r_party:       '<strong style="color:var(--accent);">🎉 Party Mode:</strong> On a neutral zone (opponent\'s or off-zone), choose between a dare or losing your next dart.',
      dp_r_darts:       '<strong style="color:var(--dim);">3 darts</strong> per player per turn.',
      // ── Rules Shooter ─────────────────────────────────────
      sht_rules_title:  '💥 BATTLE ROYAL RULES',
      sht_r_obj:        '<strong>🎯 Goal:</strong> Be the last survivor (or team)',
      sht_r_hp:         '<strong>❤️ HP:</strong> Reaches 0 → eliminated',
      sht_r_ammo:       '<strong>💥 Ammo:</strong> Required to attack',
      sht_r_ammo1:      '• Hit your zone → +1/2/3 ammo',
      sht_r_ammo2:      '• Enemy attack → -1 ammo, 1/2/3 damage',
      sht_r_bullg:      '<strong>💚 Green Bull:</strong> +2 HP or heal/revive',
      sht_r_bullr:      '<strong>❤️ Red Bull:</strong> Removes invulnerabilities + bonus choice',
      sht_r_invuln:     '<strong>🛡️ Invulnerability:</strong> Ignores damage (1 turn)',
      sht_r_last:       '<strong>⚠️ Last Stand (easy mode):</strong> At 1 HP, choose 1 survival zone',
      // ── Rules Blackjack ───────────────────────────────────
      bj_rules_title:   '🎰 BLACKDART RULES',
      bj_r_obj:         '<strong style="color:var(--gold);">Goal:</strong> Get as close to the target score as possible without going over.',
      bj_r_target:      '<strong style="color:var(--gold);">Target:</strong> Random number between 21 and 80, different each round.',
      bj_r_dealer:      '<strong style="color:var(--ok);">Dealer:</strong> Choose manually or draw randomly. The dealer stays the same throughout the game.',
      bj_r_results_h:   '<strong style="color:var(--gold);">Results:</strong>',
      bj_r_r1:          'Perfect score (= target) → +2€ (if dealer also perfect: tie)',
      bj_r_r2:          'Better than the dealer → +1€',
      bj_r_r3:          'Worse than the dealer → -1€',
      bj_r_r4:          'Exceed the target → score = 0',
      bj_r_dealer_perf: 'If dealer is perfect: all other players -2€.',
      // ── Rules Race 500 ────────────────────────────────────
      rc_rules_title:   '🏁 RACE RULES',
      rc_r_obj:         '<strong style="color:var(--accent);">Goal:</strong> Be the first to reach exactly the target score (300 or 500).',
      rc_r_turn:        '<strong style="color:var(--ok);">Turn:</strong> 3 darts. Points = number × multiplier.',
      rc_r_bust:        '<strong style="color:var(--danger);">Bust:</strong> Exceeding the target cancels the entire turn.',
      rc_r_steal:       '<strong style="color:var(--warn);">Steal:</strong> Landing exactly on an opponent\'s score steals points from them (configurable)!',
      rc_r_out:         '<strong style="color:var(--dim);">OUT:</strong> 0 pts, counts as a dart.',
      // ── Rules Bataille ────────────────────────────────────
      bt_rules_title:   '⚓ Rules — Battleship',
      bt_r_princ_h:     '🎯 Principle',
      bt_r_princ_t:     'Each team <b>secretly places their ships</b> on the board. Teams take turns firing to <b>find and sink the enemy fleet</b>.',
      bt_r_ships_h:     '🚢 Ships',
      bt_r_ships_t:     '<b>2 ships:</b> 1 outer, 1 free.<br><b>3 ships:</b> 2 outer, 1 free.<br><b>4 ships:</b> 2 outer, 2 free.<br>Each ship = 3 adjacent squares.',
      bt_r_zones_h:     '🗺️ Firing zones',
      bt_r_zones_t:     'Double / Single outer → outer ring<br>Triple / Single inner → inner ring',
      bt_r_bull_h:      '🎯 Bull & Small Bull',
      bt_r_bull_t:      'Small Bull (25) → 2 random squares.<br>Bull (50) → 3 random squares.',
      bt_r_res_h:       '💥 Resolution',
      bt_r_res_t:       'HIT if the square contains a ship. SUNK if all squares of the ship are hit. MISS otherwise.',
      bt_rules_win:     '🏆 Victory',
      bt_rules_win_t:   'First team to sink all enemy ships.',
      bt_rules_got:     'Got it!',

      // ── Setup / validation toasts ─────────────────────────────
      err_max_players:    '⚠️ Maximum {n} players',
      err_min_players:    '⚠️ Minimum {n} players',
      err_name_taken:     '⚠️ Name already taken',
      err_add_1:          '⚠️ Add at least 1 player',
      err_add_2:          '⚠️ Add at least 2 players',
      err_add_2_shuffle:  '⚠️ Add at least 2 players to shuffle',
      err_solo_max3:      '⚠️ Maximum 3 players in solo mode',
      err_team_max2:      '⚠️ Maximum 2 players per team',
      err_solo_min2:      '⚠️ Solo: minimum 2 players required',
      err_team_eq:        '⚠️ Team mode: 2 players per team required',
      err_solo_max4:      '⚠️ Maximum 4 players in solo mode',
      err_duel_max6:      '⚠️ Duel: max 6 players',
      err_duel_min2:      '⚠️ Duel: minimum 2 players',
      err_team_max6:      '⚠️ Team: max 6 players (3v3)',
      err_team_min2:      '⚠️ Team: minimum 2 players',
      err_team_same:      '⚠️ Team: same number of players on each side',
      err_team_max3:      '⚠️ Team: max 3 players per team (3v3)',
      err_solo_mode:      '⚠️ Solo mode: 2 to 4 players required',
      err_team_mode:      '⚠️ Team mode: exactly 2 players per team',
      err_solo1:          '⚠️ Maximum 1 player per team in solo mode',
      err_solo1b:         '⚠️ Solo mode: max 1 player per team!',
      err_team_max_n:     '⚠️ Maximum {n} players per team',
      err_name_dp:        '⚠️ Name already taken!',
      err_target_pos:     'Values must be positive.',
      err_target_min:     'Min target must be strictly less than max.',
      err_max6_bj:        '⚠️ Maximum 6 players',
      err_pseudo_bj:      '⚠️ Name already taken',
      err_dealer:         '⚠️ Assign a dealer',
      err_targets:        '⚠️ Check target values',
      err_min2_bj:        '⚠️ Minimum 2 players',
      err_add2_rc:        'Add at least 2 players',
      err_min2_rc:        'Minimum 2 players',
      err_max6_rc:        'Maximum 6 players',
      // ── Common buttons ────────────────────────────────────────
      start_btn:          '🎯 START',
      cancel_shot:        '↩ Cancel',
      close_btn:          'Close',
      back_btn:           '← Back',
      // ── Dynamic round / turn labels ───────────────────────────
      round_n_of:         'ROUND {r}/{t}',
      tour_n_of:          'TURN {r}/{t}',
      turn_n:             'TURN {n}',
      tour_label:         'Turn {n}',
      round_dart:         'TURN {r} · DART {d}/3',
      ckt_round_of:       'Round: {r}/{t}',
      ckt_round:          'Round: {r}',
      // ── 501 double-out modal ──────────────────────────────────
      x01_dout_title:     '🎯 Doubles attempted this turn',
      x01_dout_sub_fin:   'How many doubles did you aim at before finishing?',
      x01_dout_sub:       'How many doubles did you aim at this turn?',
      // ── Territoire history ────────────────────────────────────
      ter_bull_no_target: '💚 Green Bull (no target)',
      ter_rbull_no_tgt:   '❤️ Red Bull (no target)',
      ter_out_of_play:    '→ zone {n} (out of play)',
      ter_out_ring:       '→ {n}{r} (out of play)',
      ter_no_shots:       'No shots recorded.',
      ter_no_zones:       'No zones',
      // ── Territoire zones-drawer ───────────────────────────────
      ter_neutral_lbl:    '⬜ NEUTRAL',
      // ── DartPong ────────────────────────────────────────────
      dp_streak_msg:      '{name} — 3 zones in a row!',
      dp_bull_used:       '🎯 Bull (already used)',
      dp_bull_announced:  '🎯 BULL announced!',
      dp_shot_cancelled:  'Shot cancelled',
      dp_bull_q2:         'Did you call the bull before throwing?',
      dp_party_fail:      '{name} missed!',
      dp_no_players:      'No players added',
      // ── Shooter ───────────────────────────────────────────────
      sht_neutral_miss:   'Neutral zone',
      sht_dmg_toast:      '-{dmg} HP to {name}',
      sht_last_toast:     '{name} dropped to 1 HP! Choose your survival zone:',
      sht_invuln_label:   '🛡️ Invulnerability:',
      sht_invuln_t1:      '• Blocks all damage until next turn',
      sht_last_t1:        '• At 1 HP: choose 1 survival zone',
      sht_last_t2:        '• Only that zone can hit you',
      // ── Blackjack ────────────────────────────────────────────
      bj_dealer_toast:    '🎩 {name} is dealer!',
      // ── Bataille ─────────────────────────────────────────────
      bt_placement_title: 'Team {t} — Secret placement',
      bt_placed_toast:    '{ship} placed!',
      bt_overlap:         'Overlap not allowed!',
      bt_no_cells:        'No cells available!',
      bt_legend_title:    '📖 Legend',
      bt_leg_hit_desc:    'The dart hit a square containing an enemy ship',
      bt_leg_sink_desc:   'All 3 squares of the ship were hit — ship destroyed',
      bt_leg_miss_desc:   'No enemy ship on this square (empty, own ship, or duplicate)',
      bt_leg_sunk_desc:   'Ship out of play — all its squares were hit',
      bt_leg_sb_desc:     'Outer green circle — reveals 2 random untargeted squares',
      bt_leg_bull_desc:   'Inner red circle — reveals 3 random untargeted squares',
      // ── History Shanghai ─────────────────────────────
      shg_label_s:        'Single',
      shg_label_d:        'Double',
      shg_label_t:        'Triple',
      // ── History DartPong ──────────────────────────
      dp_bull_aimed_used: 'aimed bull (already used)',
      dp_bull_missed:     'missed bull (not called)',
      dp_hist_gage:       '→ OUT (dare accepted 🎭)',
      dp_hist_bull_sacr:  '🎯 BULL — sacrifices zone {n} ({type})',
      dp_hist_capture_h:  '❤️ captures {zone} + 🛡️',
      // ── History Shooter ─────────────────────────────
      sht_own_zone_h:     '→ own zone +{n} 💥',
      sht_no_bullets_h:   '→ no bullets',
      sht_invuln_act_h:   '→ {name} invulnerable',
      sht_revive_hist:    '→ Revived {name}',
      sht_heal_ally_h:    '→ +2 HP to {name}',

      // ── Commun ──────────────────────────────────────
      require_validate:   'Validation required',
      pp_manual_ph:       'Name without profile…',
      btn_validate:       'VALIDATE',
      press_validate:     'Turn done — Validate to continue',

      // ── Horloge ─────────────────────────────────────
      cl_title:           '🕐 CLOCK',
      cl_ordre_lbl:       '📋 ORDER',
      cl_ordre_asc:       '1 → 20',
      cl_ordre_desc:      '20 → 1',
      cl_ordre_rand:      'Random',
      cl_bull_lbl:        '🎯 BULL',
      cl_bull_none:       'None',
      cl_bull_bull:       'Bull',
      cl_bull_bulleye:    'Bull + Eye',
      cl_hits_lbl:        '🎳 HITS PER NUMBER',
      cl_hits_1:          '1 time',
      cl_hits_2:          '2 times',
      cl_hits_3:          '3 times',
      cl_skip_lbl:        '⚡ DOUBLE / TRIPLE',
      cl_skip_normal:     'Normal',
      cl_skip_skip:       'Skip 1–2 numbers',
      cl_skip_detail:     'Double = skip 1 · Triple = skip 2',
      cl_skip_bull:       '(Bull cannot be skipped)',
      cl_players:         '👥 PLAYERS (1-6)',
      cl_player_n:        'PLAYER {n}/{t}',
      cl_target:          'TARGET',
      cl_btn_simple:      'SINGLE',
      cl_btn_double:      'DOUBLE',
      cl_btn_triple:      'TRIPLE',
      cl_btn_bull:        'BULL',
      cl_btn_bulleye:     'BULL EYE',
      cl_bull_pts:        '25 pts ✓',
      cl_bulleye_pts:     '50 pts ✓',
      cl_validate_lbl:    '✅ Validation required',
      cl_replay_lbl:      '🔁 3 hits = Replay',
      cl_exploit_sub:     '3 hits in a row!',
      cl_miss:            'Miss',
      cl_undo:            'UNDO',
      cl_validate:        'Validate',
      cl_hist:            '📜',
      cl_history:         '📜 HISTORY',
      cl_next:            'Next:',
      cl_sub_advance1:    'Advance 1',
      cl_sub_advance2:    'Advance 2',
      cl_sub_advance3:    'Advance 3',
      cl_sub_valid:       '✓ valid',
      cl_sub_hit1:        '+1 hit',
      cl_sub_hit2:        '+2 hits',
      cl_sub_hit3:        '+3 hits',
      cl_wins:            'WINS!',
      cl_finished:        'Completed the clock!\nLast target:',
      cl_bull_note:       '(Bull cannot be skipped)',
      cl_validate_toast:  'Turn done — Validate to continue',
      cl_not_bulleye:     'not BullEye',
      cl_replay_msg:      'REPLAY! (3 hits)',
      cl_skip_msg:        'skip',
      cl_pct_clock:       '% clock',
      cl_miss_hist:       'Miss',
      cl_rules_title:     '📖 RULES — CLOCK',

      // ── Welcome popup ─────────────────────────────────────
      welcome_title:      'Welcome to DartVault!',
      welcome_step1_title:'Create your profiles',
      welcome_step1_desc: 'In seconds, track your stats across every game.',
      welcome_step2_title:'Jump into quick games',
      welcome_step2_desc: 'Every mode is easy to pick up, from beginner to expert.',
      welcome_step3_title:'Simple rules',
      welcome_step3_desc: 'Built-in instructions are just a tap away on each game.',
      welcome_ok:         'LET\'S GO!',
      welcome_dismiss:    'Don\'t show this again',
    }
  };

  window.DV_LANG = {
    get: function () {
      return localStorage.getItem('dartvault_lang') || 'fr';
    },
    t: function (key) {
      var lang = window.DV_LANG.get();
      return (T[lang] && T[lang][key] !== undefined) ? T[lang][key] : (T['fr'][key] || key);
    },
    apply: function () {
      var lang = window.DV_LANG.get();
      document.querySelectorAll('[data-i18n]').forEach(function (el) {
        var key = el.dataset.i18n;
        var val = window.DV_LANG.t(key);
        if (val !== undefined) el.textContent = val;
      });
      document.querySelectorAll('[data-i18n-html]').forEach(function (el) {
        var key = el.dataset.i18nHtml;
        var val = window.DV_LANG.t(key);
        if (val !== undefined) el.textContent = val;
      });
      // Placeholder inputs
      document.querySelectorAll('[data-i18n-ph]').forEach(function (el) {
        el.placeholder = window.DV_LANG.t(el.dataset.i18nPh);
      });
    }
  };
})();
